//v146 Copyright (c) 2008-2018 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
"undefined"==typeof Tynt.TIL&&"undefined"==typeof Tynt.TCL&&"undefined"==typeof Tynt.TICFL&&function(){var k=window,h=document,n={distro:"TI",id:"TI-"+(new Date).getTime()};Tynt.TIL=function(){function C(){}function Ua(a,b,c,d){var f=function(a,b,c,d,f){a.size=b||"";a.size?(b=b.split("x"),a.width=b[0],a.height=b[1]):(a.width="0",a.height="0");a.targetId=c||"";a.product=d||"inpage";f?a.distro=f:"inview"==a.product&&(a.distro="RCIV");a.iframeId=null;a.sicWindow=null};22==a.length?(this.publisherId=
a,this.options=c||{},f(this,this.options.size||"1x1",this.options.targetId||"",b)):f(this,a,b,c,d)}function ta(a,b,c){this.type=a;this.fn=b;this.once=!!c}function R(a){var b=R.options;a=b.parser[b.strictMode?"strict":"loose"].exec(a);for(var c={},d=14;d--;)c[b.key[d]]=a[d]||"";c[b.q.name]={};c[b.key[12]].replace(b.q.parser,function(a,d,h){d&&(c[b.q.name][d]=h)});return c}if(document.body){Date.now||(Date.now=function(){return(new Date).getTime()});var e={_maxRef:600,_idMacro:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
init:function(){this._icUrl=n.protocol+(Tynt.e||"")+"ic.tynt.com";this._debUrl=n.protocol+(Tynt.e||"")+"de.tynt.com/deb/v2";this._sicUrl=n.protocol+(Tynt.e||"")+"cdn-sic.33across.com/1/javascripts/sic.js";this._apUrl=n.protocol+(Tynt.e||"")+"cdn-ap.33across.com/javascripts/ap.js"},newEle:function(a,b,c,d){d=d||window;a=d.document.createElement(a);b&&this.extend(a,b);c&&this.extend(a.style,c);return a},injectScript:function(a,b,c){b=b||window;a=this.newEle("script",{async:"async",type:"text/javascript",
src:a},null,b);this.insertEle(a,c||b.document.getElementsByTagName("script")[0])},injectSicScript:function(a){this.injectScript(this._sicUrl,window,a)},injectApolloScript:function(){this.injectScript(this._apUrl)},injectSicIframe:function(a,b,c){var d={width:a.width+"px",height:a.height+"px",border:"0 none",margin:"0"};c&&this.extend(d,c);c=this.newEle("iframe",{src:"about:blank",frameBorder:"0",frameSpacing:"0",scrolling:"no"},d);this.insertEle(c,b);a.iframeId=this.eleId(c);a.sicWindow=c.contentWindow;
a=c.contentWindow.document;a.open();a.write('<!DOCTYPE html><html><head><style type="text/css">*{margin:0;padding:0;}</style></head><body><script type="text/javascript">window.Tynt = window.parent.Tynt;\x3c/script><script type="text/javascript" src="'+this._sicUrl+'">\x3c/script></body></html>');a.close()},insertEle:function(a,b){b?"script"==b.tagName.toLowerCase()?b.parentNode.insertBefore(a,b):b.appendChild(a):document.body.appendChild(a)},eleId:function(a){var b=a.id;b||(b="x33x"+Date.now(),a.id=
b);return b},_imgs:[],injectPixel:function(a,b,c){var d;try{d=h.createElement("img")}catch(f){d=document.createElement("img")}d&&(this._imgs.push(d),b&&(d.onload=b),c&&(d.onerror=c),d.src=a)},docUrl:function(){var a=this.getLink("canonical");a||(a=this.getMeta("property","og:url","name","original-source"));if(a){if(0!=a.indexOf("http")){var b=n.protocol+k.location.host+k.location.pathname,c=h.getElementsByTagName("base")[0];c&&(c=c.getAttribute("href"))&&(b=c);"/"==a.charAt(0)?(c=b.indexOf("/",9),
-1<c&&(b=b.slice(0,c))):(c=b.lastIndexOf("/"),b=9<c?b.slice(0,c+1):b+"/");a=b+a}return a}return""},getMeta:function(a,b,c,d){var f,l=null,k=null,q=h.getElementsByTagName("meta");for(f=0;f<q.length;++f)l||q[f].getAttribute(a)!==b?c&&!k&&q[f].getAttribute(c)===d&&(k=q[f].getAttribute("content")||null):l=q[f].getAttribute("content")||null;return l||k},getLink:function(a,b){var c,d,f=h.getElementsByTagName("link");for(c=0;c<f.length;++c)if(d=f[c].getAttribute("rel"),f[c].getAttribute("href")&&d&&(!b&&
0<=d.indexOf(a)||b&&d==a))return f[c].href;return null},extend:function(a,b){var c,d;for(c=1;c<arguments.length;++c)for(d in arguments[c])arguments[c].hasOwnProperty(d)&&(a[d]=arguments[c][d]);return a},isArray:function(a){return"undefined"!=typeof a&&"[object Array]"===Object.prototype.toString.call(a)},inArray:function(a,b){return 0<=this.indexOf(a,b)},toArray:function(a,b){return Array.prototype.slice.call(a,b||0)},indexOf:function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;++c)if(a[c]===
b)return c;return-1},unique:function(a){var b,c={},d=[];for(b=0;b<a.length;++b)c[a[b]]||(c[a[b]]=!0,d.push(a[b]));return d},iframeType:function(){var a=this.iframeEle(),b=ua,c=", iso:"+this.isolated();if(a)a.id&&0<=a.id.search(/google_ads?_i?frame/)?(b=6,e.clog("In same-origin iframe from DFP"+c)):(b=va,e.clog("In same-origin iframe"+c));else try{window!=window.top?"undefined"!=typeof window.$sf?(b=wa,e.clog("In SafeFrame")):(b=ca,e.clog("In cross-origin iframe")):e.clog("In top window")}catch(d){b=
ca,e.clog("iframeType: "+d.message)}return b},iframeEle:function(a){var b=null;a=a||window;try{b=a.frameElement}catch(c){}return b},iframeTop:function(){var a=window,b=null;try{for(;a!=window.top;)b=a,a=a.parent}catch(c){return null}return b?this.iframeEle(b):null},getTopWin:function(){var a=window;try{for(;a.parent!==a&&a.parent.document;)a=a.parent}catch(b){}return a},isolated:function(){var a=!0;try{"function"==typeof window.top.open&&(a=!1)}catch(b){}return a},tyntIds:function(){return this.unique(Tynt).join("~")},
getPubId:function(){for(var a=null,b=0;b<Tynt.length;++b)if("string"==typeof Tynt[b]&&22==Tynt[b].length&&0>Tynt[b].indexOf("!")){a=Tynt[b];break}return a},countIds:function(a){var b,c=0;for(b=0;b<Tynt.length;++b)Tynt[b]===a&&++c;return c},_log:function(a){"undefined"==typeof Tynt.debug&&0<k.location.search.indexOf("__tcdebugmode=1")&&k.console&&k.console.log&&(Tynt.debug=!0);if(!0===Tynt.debug||1===Tynt.debug)a.unshift("[TC]"),k.console.log.apply(k.console,a)},log:function(){n.inXOIframe()?this.clog.apply(this,
arguments):this._log(this.toArray(arguments))},clog:function(){var a=this.toArray(arguments);a.unshift(n.id);this._log(a)},callIc:function(){var a,b,c,d,f,l,g,q;if(!k._33Across.state.icDone){k._33Across.state.icDone=Va;b=this.getCookie(h.cookie,"tracertraffic");a=k.location.hash;a=/tynt=/.test(a)?a.match(/tynt=?([^?&$#]*)/)[1]:!1;d=c=this._icUrl+"/b/p?id="+this.tyntIds()+(b?"&et="+b:"")+(a?"&a="+a:"")+("string"==typeof Tynt.b?"&b="+Tynt.b:"")+"&lm="+n.type+"&ts="+Date.now()+"&dn="+n.distro+"&iso="+
(this.isolated()?"1":"0");(a=this.getMeta("property","og:image:url","property","og:image"))&&(d+="&img="+encodeURIComponent(this.trunc(a,250)));f=d;(a=this.getMeta("property","og:title"))&&a!=h.title&&(f+="&ct="+encodeURIComponent(this.trunc(a,200)));l=f;h.referrer&&(a=this.trunc(h.referrer,this._maxRef),l+="&r="+encodeURIComponent(a));g=l;if(a=h.title||k.location.hostname)a=this.trim(this.trunc(a,200)),g+="&t="+encodeURIComponent(a);q=g;if(a=this.docUrl())a=this.trunc(a,400),q+="&cu="+encodeURIComponent(a);
b=q;if(a=this.getLink("amphtml",!0))a=this.trunc(a,250),b+="&ah="+encodeURIComponent(a);e.callIc.rsp=function(){k._33Across.state.icDone=da};e.clog("Calling IC");this.injectPixel(b,e.callIc.rsp,function(){e.injectPixel(q,e.callIc.rsp,function(){e.injectPixel(g,e.callIc.rsp,function(){e.injectPixel(l,e.callIc.rsp,function(){e.injectPixel(f,e.callIc.rsp,function(){e.injectPixel(d,e.callIc.rsp,function(){e.injectPixel(c,e.callIc.rsp)})})})})})})}},callDeb:function(a){function b(a,b){e.clog("Calling DEB "+
b+(a?"":" on IC timeout"));var f=encodeURIComponent(e.trunc(h.referrer,e._maxRef));e.injectScript(e._debUrl+"?id="+e.tyntIds()+"&dn="+n.distro+"&cc="+b+"&r="+f,k)}"undefined"==typeof a&&(a=1);k._33Across.state.deDone>=a||(++k._33Across.state.deDone,this.when(function(){return k._33Across.state.icDone==da},b,{timeout:300,timeoutCallback:b,callbackData:k._33Across.state.deDone},this))},callDebX:function(a,b){function c(a,c){e[b?"log":"clog"]("Calling DEBx "+c+(a?"":" on IC timeout"));var l=encodeURIComponent(e.trunc(h.referrer,
e._maxRef));e.injectScript(e._debUrl+"?m=xch&id="+e.tyntIds()+"&dn="+n.distro+"&cc="+c+"&r="+l,k)}a||(a=10);k._33Across.state.dxDone>=a||(++k._33Across.state.dxDone,this.when(function(){return k._33Across.state.icDone==da},c,{timeout:300,timeoutCallback:c,callbackData:k._33Across.state.dxDone},this))},jsonDecode:function(a){if("function"!=typeof Array.prototype.toJSON)return JSON.stringify(a);var b=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=b;return a},
getCookie:function(a,b){for(var c=b+"=",d=a.split(";"),f=0;f<d.length;f++){for(var l=d[f];" "==l.charAt(0);)l=l.substring(1,l.length);if(0==l.indexOf(c))return l.substring(c.length,l.length)}return null},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},trunc:function(a,b){var c,d;if(!a||a.length<=b)return a;c=a.substring(0,b);for(d=1;3>=d;++d)if("%"==c.charAt(c.length-d))return c.substring(0,c.length-d);return c},when:function(a,b,c,d){var f,l,h,q=null,e=null,g=a();c=c||{};f=c.interval||50;l=c.timeout;
h=c.timeoutCallback||function(){};if(g)return b.call(d,g,c.callbackData),!0;q=k.setInterval(function(){if(g=a())k.clearInterval(q),k.clearTimeout(e),b.call(d,g,c.callbackData)},f);l&&(e=k.setTimeout(function(){k.clearInterval(q);h.call(d,g,c.callbackData)},l));return!1},prob:function(a){a=parseFloat(a)||0;return Math.random()<a}},Va=1,da=2,ua=0,ca=3,wa=4,va=5;n.type=0;n.inIframe=function(){return this.type>ua};n.inSOIframe=function(){return this.type>=va&&6>=this.type};n.inXOIframe=function(){return this.type>=
ca&&this.type<=wa};n.init=function(){this.type=e.iframeType();this.inSOIframe()&&(k=e.getTopWin(),h=k.document);k._33Across||(k._33Across={});k._33Across.state||(k._33Across.state={icDone:0,deDone:0,dxDone:0,ivDone:!1});"https:"===k.location.protocol?(this.isSecure=!0,this.protocol="https://"):(this.isSecure=!1,this.protocol="http://");e.init();this.isolated=e.isolated();k._33Across.pvTs||(k._33Across.pvTs=Date.now())};if("undefined"===typeof t)var t={afterIpBlockCheck:[],afterDynamicConfig:[],afterCheckModules:[],
afterProtectTynt:[],afterDynamicConfigAndDocumentLoaded:[]};var v=function(a,b){if("undefined"!==typeof t&&t.hasOwnProperty(a)&&t[a].hasOwnProperty("length"))for(var c=0;c<t[a].length;c+=1)if("function"===typeof t[a][c])t[a][c](b)};Tynt.settings||(Tynt.settings={_error:0,_pending:!1,_pubId:null,_scUrl:"https://"+(Tynt.e||"")+"sc.tynt.com/script/sc/",_settings:{},_copy:null,isReady:function(){return 0===this._error&&null!=this._copy},get:function(){return this._settings},pubId:function(){null==this._pubId&&
(this._pubId=e.getPubId());return this._pubId},download:function(){var a,b;C.adapt(Tynt.cmd);this._pending||this.isReady()||(a=this,Tynt.getConfig=function(){return a.isReady()?a._copy:null},Tynt.sc=function(c){clearTimeout(b);a._error=c.fl||0;0===a._error?(a._init(c),e.log("Settings downloaded",a._copy),Tynt.cmdFlush()):e.log("ERROR: Settings download failed: ",a._error);a._pending=!1},this.pubId()&&(e.log("Downloading settings"),this._pending=!0,e.injectScript(this._scUrl+this.pubId()+".js"),b=
setTimeout(function(){Tynt.sc({fl:1})},1E4)))},_init:function(a){a=a||{};!1!==a.d?(Tynt.o&&e.extend(a,Tynt.o),this._ovr(a)):a=Tynt.i||k.tyntVariables||{};this._def();e.extend(this._settings,a);this._val();this._copy="undefined"!==typeof JSON&&"function"==typeof JSON.parse&&"function"==typeof JSON.stringify?JSON.parse(e.jsonDecode(this._settings)):this._settings},_ovr:function(a){if(e.isArray(Tynt.overrides))for(var b=0;b<Tynt.overrides.length;b++)"object"==typeof Tynt.overrides[b]&&e.extend(a,Tynt.overrides[b])},
_def:function(){this._settings.d=!0;this._settings.a=!0;this._settings.ad=!0;this._settings.aw=8;this._settings.cc=0;this._settings.b=!1;this._settings.ap="Read more:";this._settings.as="";this._settings.st=!1;this._settings.su=!0;this._settings.w=!1;this._settings.f=!1;this._settings.ss=""},_val:function(){this._settings.a||(this._settings.a=!1);6<this._settings.cc&&(this._settings.cc=0);8>this._settings.aw&&(this._settings.aw=8);this._settings.su||(this._settings.su=!1);this._settings.w&&!this._twUser(this._settings.w)&&
(this._settings.w=!1);this._settings.f&&!this._fbUser(this._settings.f)&&(this._settings.f=!1);0<this._error&&(this._settings.a=!1,this._settings.b=!1)},_twUser:function(a){return/^\w{1,15}$/.test(a||"")},_fbUser:function(a){return/^[\w.]{2,}$/.test(a||"")}});"undefined"==typeof Tynt.cmd&&(Tynt.cmd=[]);C.prototype.push=function(){C.adapt(arguments);C.exec(arguments)};C.exec=function(a){e.log("Executing commands",a);try{for(var b=0;b<a.length;++b)if("function"==typeof a[b])a[b]();else"object"==typeof a[b]&&
"function"==typeof a[b].fn&&a[b].fn()}catch(c){e.log("ERROR: Tynt.cmd failed: ",c)}};C.adapt=function(a){var b,c;if(e.isArray(a))for(b=0;b<a.length;++b)"object"==typeof a[b]&&(c=a[b].publisherId,"string"!=typeof c||22!=c.length||e.inArray(Tynt,c)||(Tynt.push(c),e.log("Adapted",c)))};"undefined"==typeof Tynt.cmdFlush&&(Tynt.cmdFlush=function(){var a=Tynt.cmd;if(!a||e.isArray(a))Tynt.cmd=new C,a&&0<a.length&&C.exec(a)});Tynt.ads||(Tynt.ads={_slots:[],display:function(a,b,c,d){"string"==typeof a?this.addSlot(new Ua(a,
b,c,d)):e.log("ERROR: Invalid product")},getSlot:function(a){return(a=this.getSlots(a))&&0<a.length?a[0]:null},getSlots:function(a){for(var b=[],c=0;c<this._slots.length;++c)this._slots[c].sicWindow===a&&b.push(this._slots[c]);return 0<b.length?b:null},addSlot:function(a){var b=null,c=Tynt.settings.get(),d="Injecting sic/"+a.product;if(c&&c.sic)if(a.sicWindow=window,"inview"==a.product&&this.ivReady(c,a))this.ivDone(!0),this._slots.push(a),e.log(d,a),e.injectSicScript(),e.callDebX(null,!0);else{if("inpage"==
a.product&&this.ipReady(c)||"infeed"==a.product&&this.ifReady(c))a.targetId&&(b=document.getElementById(a.targetId)),n.inIframe()?(this._setIframeId(a),this._slots.push(a),e.log(d,a),e.injectSicScript(b)):(this._slots.push(a),e.log(d+" into iframe",a),e.injectSicIframe(a,b,"infeed"==a.product?{position:"absolute"}:null))}else e.log("ERROR: settings or .sic undefined",c)},_setIframeId:function(a){var b=e.iframeTop();b&&(a.iframeId=e.eleId(b))},ivDone:function(a){!0===a&&(k._33Across.state.ivDone=!0);
return k._33Across.state.ivDone},ivReady:function(a,b){var c=!1,d;!this.ivDone()&&e.isArray(a.p)&&e.inArray(a.p,"sic_v1")&&a.sic.products&&a.sic.products.inview&&(d=a.sic.products.inview.install_method||a.sic.install_method,"TI"==b.distro?"On Page"==d&&(c=!0):"On Page"!=d&&(c=!0));return c},ipReady:function(a){return a.sic.products&&a.sic.products.siab},ifReady:function(a){return a.sic.products&&a.sic.products.infeed},_events:[],on:function(a,b){this._events.push(new ta(a,b,!1))},once:function(a,
b){this._events.push(new ta(a,b,!0))},off:function(a,b){for(var c=0;c<this._events.length;++c)this._events[c]&&this._events[c].type===a&&this._events[c].fn===b&&(this._events[c]=null)},emit:function(a){var b,c;for(b=0;b<this._events.length;++b)this._events[b]&&this._events[b].type===a&&(c=this._events[b],c.once&&(this._events[b]=null),c.fn.apply(c,Array.prototype.slice.call(arguments,1)))},_targeting:{},setTargeting:function(a,b){this._targeting[a]=b},getTargeting:function(a){return this._targeting[a]},
getTargetingKeys:function(){return Object.keys(this._targeting)}});R.options={strictMode:!1,key:"source protocol authority userInfo user password host port relative path directory file query anchor".split(" "),q:{name:"queryKey",parser:/(?:^|&)([^&=]*)=?([^&]*)/g},parser:{strict:/^(?:([^:\/?#]+):)?(?:\/\/((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?))?((((?:[^?#\/]*\/)*)([^?#]*))(?:\?([^#]*))?(?:#(.*))?)/,loose:/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/}};
n.init();var p=h.body,w=h.documentElement,S=k.eval("/*@cc_on!@*/false"),xa=function(a,b){for(var c="",d=0;d<b;d++)c+=a;return c},D=xa("a",50),E=(Tynt.e||"")+"ic.tynt.com",Wa=(Tynt.e||"")+"cdn.tynt.com",ea=E+"/b/s",ya=(Tynt.e||"")+"platform.33across.com",r=function(a,b,c){a=h.createElement(a);e.extend(a,b);e.extend(a.style,c);return a},B,M;k.addEventListener?(B=function(a,b,c){a.addEventListener(b,c,!1)},M=function(a,b,c){a.removeEventListener(b,c,!1)}):(B=function(a,b,c){a.attachEvent("on"+b,c)},
M=function(a,b,c){a.detachEvent("on"+b,c)});var N=function(a,b){var c=k.location.hostname.split("."),d,f=2;do d=c.slice(c.length-f,c.length).join("."),d=a+";path=/;domain=."+d+";"+b,h.cookie=d,f++;while(-1==h.cookie.indexOf(a)&&f<=c.length);-1==h.cookie.indexOf(a)&&(h.cookie=a+";path=/;"+b)},fa=function(a){"complete"==h.readyState?a():B(k,"load",function(b){setTimeout(function(){"undefined"!=typeof h.readyState||S||(h.readyState="complete");a()},10)})},u=function(a,b){var c=[],d=function(a,b){var c=
n.protocol+a.replace("id="+D,"id="+e.tyntIds());-1<c.indexOf(E+"/b/p?")&&"string"==typeof Tynt.b&&(c+="&b="+Tynt.b);var d=new Image(1,1);b&&(d.onerror=b);d.src=c};u=function(a,b){c.push([a,b])};fa(function(){u=d;for(var a=0;a<c.length;a++)u(c[a][0],c[a][1]);c=null});u(a,b)},Xa=function(a){a=r("script",{async:"async",src:n.protocol+a});var b=h.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},za=function(a){var b=[],c="",d;for(d in a)a.hasOwnProperty(d)&&(b.push(c,d,"=",a[d]),c="&");
return b.join("")},I=function(a){for(var b=0,c=100>a.length?a.length:100,d=0;d<c;d++)b+=a.charCodeAt(d);a=Math.floor(3844*Math.random());c=Math.abs(Date.now()-12281184E5);return Aa(c,7)+Aa((b+a)%3844,2)},Ba=function(a){if(62>a)return"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(this);var b=Math.floor(a/62);a-=62*b;return 62<=b?Ba(b)+"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a):"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(b)+
"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a)},Aa=function(a,b){var c=Ba(a);return xa("0",b-c.length)+c},T=function(a){return(a=e.trim(a))?a.split(/\s+/i).length:0},U=e.trim((h.title||k.location.hostname).toString()).replace(new RegExp(k.location.hash,"g"),""),Ca=function(a){var b=a.trace_type;delete a.trace_type;var c=a.g;delete a.g;for(var d=[],f="id wc f w h t c".split(" "),l=0;l<f.length;l++){var h=f[l],k=a[h];k&&d.push([h,encodeURIComponent(k).replace(/\'/g,"%27")]);
delete a[h]}for(var e in a)a.hasOwnProperty(e)&&(f=a[e])&&d.push([e,encodeURIComponent(f).replace(/\'/g,"%27")]);a=[];var l=2048-((n.protocol+E+"/a/t/x#?").length+(3+c.length)+5),h=d.length,g=k=0,m=0,p,y,z,r,G=0;for(a[G]={g:c,tp:null};k<h&&35>a.length;)p=d[k][0],e=d[k][1],z=p.length+2,y=l-z-g,0<y?(f=e.substring(m,m+y),r=f.slice(-2).indexOf("%"),-1<r&&(f=e.substring(m,m+y-2+r),g+=r+2),g+=f.length+z,m+=f.length,a[G][p]=f):g=l,g>=l&&(a[++G]={g:c,p:G},g=0),m>=e.length&&(k++,m=0);a[0].tp=a.length;u(E+
"/b/t/"+b+"?"+za(a[0]));for(c=1;c<a.length;c++)u(E+"/b/x/"+b+"?"+za(a[c]))},ga=function(){var a=[];return function(b){for(var c=a.length-1;0<=c;c--)if(a[c]==b)return!1;a.unshift(b);3<a.length&&a.pop();return!0}},Ya=ga(),Za=ga(),$a=function(a){var b,c=function(a){k.removeEventListener("blur",c,!1);ha(b);return!0};return function(a){b=a.target||a.srcElement;k.removeEventListener("blur",c,!1);"IMG"==b.nodeName&&"A"!=b.parentNode.nodeName&&(k.addEventListener("blur",c,!1),setTimeout(function(){h.removeEventListener("blur",
c,!1)},1E4));return!0}}(),Da=function(a){ha(a.target||a.srcElement,!0)},V,Ea=function(a){a=a.target||a.srcElement;V="IMG"==a.nodeName?a:null},ia=function(a){var b=function(a){return"number"==typeof a.pageX?{x:a.pageX-(w.scrollLeft?w.scrollLeft:p.scrollLeft),y:a.pageY-(w.scrollTop?w.scrollTop:p.scrollTop)}:{x:a.clientX,y:a.clientY}},c=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=p.clientWidth||a.y>=p.clientHeight},d=function(a){a=b(a);return 0>=a.x||0>=a.y||a.x>=w.clientWidth||a.y>=w.clientHeight},
f=function(a){return"#document"==a.target.nodeName},l=function(a){a=b(a);return 4>=a.x||4>=a.y||a.x>=w.clientWidth-4||a.y>=w.clientHeight-4},k=function(a){k=navigator.userAgent.match("MSIE")?h.compatMode&&-1!=h.compatMode.indexOf("CSS")?d:c:navigator.userAgent.match("Firefox")?f:l;k(a)};return function(a){V&&k(a)&&(ha(V),V=null);return!0}}(),Fa=function(){return/tracer=test|tracer=no_tracing|disableTracer=/.test(k.location.href)||/disableTracer=y/.test(h.cookie)},Ga=function(){if(h.referrer){var a=
k.location.hostname;return R(h.referrer).host===R(a).host}return!1};Tynt.ci=function(){var a;return function(b,c){a=c||a;var d=ea+["?ci=",b,"&id=",D,"&g=",a,"&r=",encodeURIComponent(h.referrer),"&ts=",Date.now()].join("");u(d)}}();Tynt.st=function(){var a;return function(b,c,d,f){a=d||a;b=[ea,"?",encodeURIComponent(b),"=",encodeURIComponent(c),"&id=",D,"&g=",a,"&r=",encodeURIComponent(h.referrer),"&href=",encodeURIComponent(k.location.href),"&ts=",Date.now()];c="";if(f){c=[];d="";for(var l in f)f.hasOwnProperty(l)&&
(c.push(d,encodeURIComponent(l),"=",encodeURIComponent(f[l])),d="&");c="&"+c.join("")}u(b.join("")+c)}}();var ja;Tynt.c?ja=function(){}:(Tynt.c=!0,Tynt.m=Tynt.m||[],Tynt.n=Tynt.n||[],ja=function(){var a=!0,b,c=function(b,c){var l={id:D,wc:T(c),c:c,f:a?1:0,t:U};e.extend(l,b);a=!1;Ca(l)};k.addEventListener?(navigator.userAgent.match(/Firefox\/2\b/)||p.addEventListener("copy",Da,!1),k.addEventListener("mousedown",Ea,!1),k.addEventListener("dragleave",ia,!1),k.addEventListener("dragexit",ia,!1),h.addEventListener("contextmenu",
$a,!1)):(p.attachEvent("oncopy",Da),h.getElementsByTagName("html")[0].attachEvent("ondragleave",ia),p.attachEvent("onmousedown",Ea));-1!==h.cookie.indexOf("tracertraffic=")&&(h.referrer&&-1!=h.referrer.indexOf(k.location.host)||N("tracertraffic=0","expires=Thu, 01 Jan 1970 00:00:00 GMT"));e.callIc();e.callDeb();return function(a,f){if(!h.getElementById("tyntSh")){var l,g,q;f&&(h.selection&&h.selection.createRange?(g=h.selection.createRange(),q=g.duplicate(),l=g.text):(g=k.getSelection(),q=0<g.rangeCount&&
g.getRangeAt(0),l=g.toString()));var m=a.src;if(m&&!l&&Za(m)){g={trace_type:3,g:I(m),w:a.width,h:a.height};for(q=0;q<Tynt.n.length;q++)Tynt.n[q](g,m);c(g,m)}else if(l&&e.trim(l).length&&"TEXTAREA"!=a.nodeName&&"INPUT"!=a.nodeName){m=Ya(l);g={trace_type:1};m&&(b=I(l));g.g=b;for(var p=!0,n=0;n<Tynt.m.length;n++)p=p&&Tynt.m[n](g,l,q,m);m&&p&&c(g,l)}}}});var W=function(a){a=a.charCodeAt(0);return 3584<=a&&3711>=a||11904<=a&&12591>=a||12688<=a&&40959>=a||63744<=a&&64255>=a||65072<=a&&65103>=a||131072<=
a&&173791>=a||194560<=a&&195103>=a},Ha=function(a){a=a.getElementsByTagName("script");for(var b=a.length-1;0<=b;b--){var c=a[b];c.parentNode.removeChild(c)}},J=function(a,b){var c=e.docUrl(),c=c&&!1!==g.c?c:k.location.href,c=c.replace(/#(i|a)xzz=?(.*)$/g,""),c=c+"#"+("ixzz"+a);b&&(c+="&"+b);return c},ka=function(a){return a.replace(/^\s+|\s+$/g,"")},la=h.defaultView,ma=S?!h.compatMode||-1==h.compatMode.indexOf("CSS"):!1,ab=S?!("XMLHttpRequest"in k):!1,na=function(a){na="undefined"!=typeof la&&"undefined"!=
typeof la.getComputedStyle?function(a){return la.getComputedStyle(a,"")}:function(a){return a.currentStyle};return na(a)},bb={t:3,p:6,w:7,f:8,i:9,l:10,g:11,ssbt:12,ssbf:13,ssbp:14,ssbl:15,ssbg:16},Ia=function(a){var b=new Date(Date.now()+864E5);N("tracertraffic="+a.toString(),"expires="+b.toUTCString())},cb=function(){if(Tynt.v)return!1;Tynt.v=!0;var a=k.location.href.match(/ixzz=?([^?&$#]*)/);if((a=(a&&2==a.length?a[1]:null)||Tynt.h)&&!Ga()){var b;(b=k.location.href.match(/ixzz=?([^?$#]*)/))?(b=
b[1].match(/&([^?$]*)/),b=Tynt.k?Tynt.k.charAt(1):b&&b[1]?b[1]:null):b=null;a=E+"/b/v"+["?g=",a,/\?trace_owner_view/.test(k.location.href)?"&o=y":"","&id=",D,b?"&s="+b:"","&r=",encodeURIComponent(h.referrer),"&ts=",Date.now()].join("");u(a);Ia(bb[b]||1);return!0}return!1},H=n.protocol+(Tynt.e||"")+"cdn.tynt.com/images/ss/",db=n.protocol+"cdn.tynt.com/close.html",Ja="undefined"!==typeof createImageMeme,eb=/Mobile|iP(hone|od|ad)|Android|BlackBerry|Tablet|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/,
A=A||"",A=A+["#tyntSh div,#tyntSh span,#tyntSh img,#tyntSh a,div#tyntSh{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;line-height:1;background:0;text-align:left}#tyntSh img,#tyntSh span{display:inline}#tyntSh div,div#tyntSh{display:block}div#tyntSh{z-index:9999999;position:absolute;height:62px;margin:10px;overflow:visible;background:#FFF;border-radius:5px;text-align:center;box-shadow: 0 2px 6px rgba(0,0,0,0.5)}div#tyntShTr{margin:-11px auto 0 auto;width:0;height:0;border-left:10px solid transparent;border-right:10px solid transparent;border-bottom:11px solid #F1F1F1}img#tyntShTw,img#tyntShP,img#tyntShFb,img#tyntShLi,img#tyntShGp{cursor:pointer;height:28px;width:28px;margin:3px 3px 2px 3px;vertical-align:bottom}div#tyntShPTL,div#tyntShHFL{color:#888;text-decoration:none;margin:0 0 2px 0;background-color:#F1F1F1;padding:2px 4px;border-radius:5px 5px 0 0}div#tyntShHFL{text-align:right;border-radius:0 0 5px 5px;margin:2px 0 0 0}div#tyntShHFL,span#tyntShHFLs,div#tyntShPTL{font:normal 8px Arial}",
"span#tyntShHFLs{cursor:pointer;"+(ma?"text-decoration:underline":"")+"}","span#tyntShHFLs:hover{color:#555;text-decoration:underline}div#tyntShCB{position:absolute;cursor:pointer;width:14px;height:14px;top:0;right:0;background-position:0 -14px;background-repeat:no-repeat}div#tyntShCB:hover{background-position: 0 0}"].join(""),x=function(){var a,b;return function(c,d,f){a=d||a;b=f||b;c=ea+["?w=",c,"&id=",D,"&g=",a,"&wc=",b,"&r=",encodeURIComponent(h.referrer),"&ts=",Date.now()].join("");u(c)}}(),
X=function(){return eb.test(navigator.userAgent||navigator.vendor||k.opera)},K=function(a){return-1<(g.ss||"").indexOf(a)},Ka=function(){return(g.ss||"").replace("p","").replace("m","").length},Y=function(a,b){return b.length>a?b.slice(0,a-1)+"\u2026":b},fb=function(a,b,c){"undefined"===typeof c&&(c="w");b=J(b,c);return b=Y(114,a)+" "+b},m={words:0,_content:"",guid:null,isBar:function(a){return!!(a||"").toString().match(/ssb/)},getContentFor:function(a){return m.isBar(a)?"":m._content},setContent:function(a){m._content=
a},getGuid:function(){return this.guid?this.guid:I(k.location.toString())},twitter:function(a,b,c){return r("img",{src:H+"t.png",title:"tweet this",id:a,onclick:function(a){k.open(n.protocol+"twitter.com/home?status="+encodeURIComponent(fb(m.getContentFor(c),m.getGuid(),c)),"tweet","width=723,height=251");x(b,m.getGuid(),m.words)}})},facebook:function(a,b,c){return r("img",{src:H+"fb.png",title:"share on Facebook",id:a,onclick:function(a){a=["https://www.facebook.com/dialog/feed?app_id=158472647611546&link=",
encodeURIComponent(J(m.getGuid(),c)),"&description=",encodeURIComponent(Y(140,m.getContentFor(c))),"&redirect_uri=",encodeURIComponent(db)].join("");k.open(a,"fbshare","width=985,height=450");x(b,m.getGuid(),m.words)}})},linkedin:function(a,b,c){return r("img",{src:H+"li.png",title:"share on LinkedIn",id:a,onclick:function(a){a=[n.protocol+"www.linkedin.com/shareArticle?mini=true","&url=",encodeURIComponent(J(m.getGuid(),c)),"&title=",U];m.getContentFor(c)&&(a.push("&summary="),a.push(encodeURIComponent(Y(255,
m.getContentFor(c)))));a=a.join("");k.open(a,"lishare","width=520,height=450");x(b,m.getGuid(),m.words)}})},googleplus:function(a,b,c){return r("img",{src:H+"gp.png",title:"share on Google+",id:a,onclick:function(a){a=["https://plus.google.com/share?url=",encodeURIComponent(J(m.getGuid(),c))].join("");k.open(a,"gpshare","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600");x(b,m.getGuid(),m.words)}})},pinterest:function(a,b,c){}},oa=function(a,b,c){var d=a.createElement("style");
d.id=b;d.type="text/css";b=a.createTextNode(c);d.styleSheet?d.styleSheet.cssText=b.nodeValue:d.appendChild(b);a.getElementsByTagName("head")[0].appendChild(d)},La=function(a,b,c){var d,f=function(a,b,c){m.guid=b;m.setContent(a);m.words=T(a);if(!(h.getElementById("tyntSh")||8>m.words)){x(0,m.guid,m.words);var f;if(h.selection&&h.selection.createRange){c=h.selection.createRange();var e=ma?"offset":"bounding";f=[];f[0]=c[e+"Left"]+(w.scrollLeft||p.scrollLeft);f[1]=c[e+"Top"]+(w.scrollTop||p.scrollTop);
f[2]=c.boundingHeight}else{a=r("span",{},{display:"inline"});b=c.startContainer;var g=c.endContainer,n=c.endOffset;try{e=h.createRange();e.setStart(g,n);e.setEnd(g,n);e.surroundContents(a);var y,z,u,G,t,v,n={top:0,left:0,bottom:0},F=a&&a.ownerDocument;F?(t=F.documentElement,"undefined"!==typeof a.getBoundingClientRect&&(n=a.getBoundingClientRect()),v="scrollTo"in F&&F.document?F:9===F.nodeType?F.defaultView||F.parentWindow:!1,y=n.top,z=n.left,u=n.right-n.left,G=n.bottom-n.top,"fixed"!=na(a).position&&
(y+=v.pageYOffset||t.scrollTop||0,z+=v.pageXOffset||t.scrollLeft||0),y+=t.clientTop||0,z+=t.clientLeft||0,f=[z,y,u,G]):f=null;f[2]=a.offsetHeight;a.parentNode.removeChild(a);e.detach();b.parentNode.normalize();g.parentNode.normalize()}catch(A){}"undefined"!=typeof k.getSelection().setBaseAndExtent&&k.getSelection().setBaseAndExtent(c.startContainer,c.startOffset,c.endContainer,c.endOffset)}d.style.left=f[0]+"px";d.style.top=Math.max(f[1]+f[2],3)+"px";p.insertBefore(d,p.firstChild);B(p,"mousedown",
L);B(p,"touchstart",L)}};(function(){h.getElementById("tyntShCSS")||oa(h,"tyntShCSS",A);d=r("div",{id:"tyntSh"},{width:Math.max(80,34*Ka())+"px"});ma||d.appendChild(r("div",{id:"tyntShTr"}));var a=r("div",{id:"tyntShPTL",innerHTML:"Powered by 33Across"});d.appendChild(a);a=r("div",{id:"tyntShHFL"});a.appendChild(r("span",{id:"tyntShHFLs",innerHTML:"Don't show again",onclick:gb}));var b=r("div",{id:"tyntShCB",title:"close",onclick:hb},{backgroundImage:"url("+(H+"x.png")+")"});K("f")&&d.appendChild(m.facebook("tyntShFb",
4,"f"));K("t")&&d.appendChild(m.twitter("tyntShTw",3,"w"));K("l")&&d.appendChild(m.linkedin("tyntShLi",8,"l"));K("g")&&d.appendChild(m.googleplus("tyntShGp",9,"g"));if(Ja){var c=r("img",{src:H+"pi.png",title:"pin it",id:"tyntShP",onclick:function(){createImageMeme(void 0,void 0)}});Ja&&d.appendChild(c)}X()||d.appendChild(a);d.appendChild(b)})();f(a,b,c);La=f},hb=function(a){L();x(2)},L=function(a){var b=h.getElementById("tyntSh"),c=a?a.target||a.srcElement:{id:""};!b||-1<c.id.indexOf("tyntSh")||(M(p,
"mousedown",L),M(p,"touchstart",L),p.removeChild(b),a&&x(1))},gb=function(a){L();a=new Date(Date.now()+31536E7);N("TyntSpeedShareHide=true","expires="+a.toUTCString());x(5)},Z=function(){return!ab&&-1==h.cookie.indexOf("TyntSpeedShareHide=true")},ib=function(a,b,c){Ka()&&setTimeout(function(){Z()&&La(b,a.g,c)},1);return!0};if("undefined"===typeof g)var g;t.afterDynamicConfigAndDocumentLoaded.push(function(a){if(a&&a.ssb){oa(h,"tyntSbCSS",".tynt-speedshare-bar img{margin:0 3px;}");var b;var c=h;b=
ka("tynt-speedshare-bar");if(c.getElementsByClassName)b=c.getElementsByClassName(b);else if(c.querySelectorAll)b=c.querySelectorAll("."+b);else{for(var c=c.getElementsByTagName("*"),d=[],f=0;f<c.length;f++)c[f].className.match(b)&&d.push(c[f]);b=d}d=!1;for(f=0;f<b.length;f++)c=b[f],-1<a.ssb.indexOf("f")&&(c.appendChild(m.facebook("tyntSbFb",16,"ssbf")),d=!0),-1<a.ssb.indexOf("t")&&(c.appendChild(m.twitter("tyntSbTw",17,"ssbt")),d=!0),-1<a.ssb.indexOf("l")&&(c.appendChild(m.linkedin("tyntSbLi",19,
"ssbl")),d=!0),-1<a.ssb.indexOf("g")&&(c.appendChild(m.googleplus("tyntSbGp",20,"ssbg")),d=!0);d?x(14):x(15)}});var aa=[],O=[],Ma=[{x:970,y:250},{x:300,y:600},{x:300,y:1050},{x:970,y:90},{x:300,y:250},{x:970,y:250},{x:970,y:90},{x:180,y:150},{x:160,y:600},{x:728,y:90},{x:120,y:60},{x:88,y:31}],Na=[/:\/\/[^\/]*?outbrain\.com/,/:\/\/ads\.yldmgrimg\.net/,/:\/\/[^\/]*?cdn\.adblade\.com/,/:\/\/[^\/]*?googlesyndication\.com/],A=A||"",A=A+["div.tyntShIh,.tyntShIh div,.tyntShIh span{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;line-height:1;background:0;text-align:left}.tyntShIh img,.tyntShIh span{display:inline}.tyntShIh div,div.tyntShIh{display:block;outline:0}",
"div.tyntShIh{position:absolute;cursor:default;background:transparent url("+(H+"pi.png")+") no-repeat;width:43px;height:21px;opacity:0;filter:alpha(opacity=0);z-index:9999999;-webkit-transition:opacity 0.5s;-moz-transition:opacity 0.5s}","div.tyntIhHover{opacity:1;filter:alpha(opacity=100);cursor:pointer}"].join(""),jb=function(a){a.getElementById("tyntShCSS")||oa(a,"tyntShCSS",A)},kb=function(a){return n.protocol+"pinterest.com/pin/create/button/?url="+encodeURIComponent(J(I(a.src),"i"))+"&media="+
a.src+"&description="+encodeURIComponent(Y(500,ka(a.title||a.alt)))},lb=function(a){if(g&&"undefined"!==typeof g.sspe){0===O.length&&(O=g.sspe.split(","));if(O.length!==aa.length)for(var b=0;b<O.length;b+=1)aa.push(new RegExp(O[b]));for(b=0;b<aa.length;b+=1)if(a.getAttribute("src")&&aa[b].test(a.getAttribute("src")))return!0}return!1},mb=function(a){var b,c;for(b=0;b<Na.length;b++)if(Na[b].test(a.src))return!0;for(b=0;b<Ma.length;b++)if(c=Ma[b],a.width===c.x&&a.height===c.y)return!0;return!1},nb=
function(){if(!Fa()&&Z()&&K("p")){var a=function(b){var c=b.document,d=null,f,e=null,h,m,n,p;f=c.createElement("div");f.className="tyntShIh";c.body.appendChild(f);B(f,"click",function(){"tyntShIh tyntIhHover"==f.className&&Z()&&(k.open(kb(e)),x(7))});jb(c);B(c,"mouseover",function(a){a||(a=b.event);a=b.event?a.srcElement:a.target;!("IMG"===a.nodeName&&80<=a.height&&80<=a.width&&0!==a.src.indexOf("data:"))||mb(a)||lb(a)||"nopin"===a.getAttribute("nopin")||"nopin"===a.nopin||a===e&&f.showing||(null!==
e&&e!==a&&r(),e=a,e.__tyntPinItShow=!0,null!==d&&clearTimeout(d),d=setTimeout(function(){if(e.__tyntPinItShow&&Z()){var a=e,c=b.document,d=a.getBoundingClientRect(),h=(d.right+d.left+a.width)/2,k=(d.top+d.bottom+a.height)/2;a:{var g={};for(g.x=h;g.x>d.left;g.x-=20)for(g.y=k;g.y>d.top;g.y-=20)if(c.elementFromPoint(g.x,g.y)===a){d=g;break a}g.x=-1;g.y=-1;d=g}for(;d.y<=k&&c.elementFromPoint(d.x,d.y)===a;)d.y++;for(d.y--;d.x<=h&&c.elementFromPoint(d.x,d.y)===a;)d.x++;d.x--;a=b.document.documentElement;
d={x:d.x+((b.pageXOffset||a.scrollLeft||0)+(a.clientLeft||0)),y:d.y+((b.pageYOffset||a.scrollTop||0)+(a.clientTop||0))};f.style.left=d.x-45+"px";f.style.top=d.y-22+"px";f.className="tyntShIh tyntIhHover";f.showing=!0;e.__tyntPinItRecorded||x(6);e.__tyntPinItRecorded=!0}},"undefined"!==typeof g&&"undefined"!==typeof g.pt&&"i"==g.pt?0:1E3),B(c,"mousemove",p))});p=function(a){a=c.elementFromPoint(a.clientX,a.clientY);a!=e&&a!=f&&r()&&M(c,"mousemove",p)};var r=function(){return f.showing?(e.__tyntPinItShow=
!1,f.showing=!1,f.className="tyntShIh",setTimeout(function(){f.style.left="-100px"},600),!0):!1};h=c.getElementsByTagName("iframe");for(n=h.length-1;0<=n;n--){m=h[n];try{m.src&&0!==m.src.indexOf(k.location.protocol+"//"+k.location.hostname)||"nopin"===m.getAttribute("nopin")||"nopin"===m.nopin||a(m.contentWindow)}catch(t){k.console&&Tynt.debug&&console.log("Bad iframe access",t,m)}}};a(k)}},Oa={sic_v1:function(){Tynt.ads.display("","","inview","TI")},track_selections:function(){var a=ga();B(h,"mouseup",
function(b){b="";h.selection&&h.selection.createRange?(selection=h.selection.createRange(),b=selection.text):b=k.getSelection().toString();b=e.trim(b);b.length&&a(b)&&(b={id:D,g:I(b),wc:T(b),c:b.slice(0,2E3),t:U,trace_type:2},Ca(b))})},track_attribution_views:function(){trackAttributionView=!0}};t.afterDynamicConfig.push(function(){var a,b,c=g.p;g.apollo&&(e.log("Injecting Apollo"),e.injectApolloScript());if(c)for(a=0;a<c.length;a++)if((b=c[a])&&"function"===typeof Oa[b])Oa[b]();else e.log('ERROR: Unknown module: "'+
b+'"');"function"===typeof v&&v("afterCheckModules")});var ob=ya+"/ipb.js",pa=function(){return-1!==h.cookie.indexOf("ty_attributionBlockedByIp=t")?!0:!1},Pa,pb=function(){Pa=setTimeout(function(){v("afterIpBlockCheck",g)},3E3);Xa(ob)};Tynt.ipb=function(a){clearTimeout(Pa);var b=!1;if("[object Array]"===Object.prototype.toString.apply(g.ipb)){for(var c=0;c<g.ipb.length;c++)if(a===g.ipb[c]){b=!0;break}a=b;b=new Date;b.setHours(b.getHours()+1);b="expires="+b.toGMTString();N("ty_attributionBlockedByIp="+
(!0===a?"t":"f"),b)}v("afterIpBlockCheck",g)};var Qa=(Tynt.e||"")+"ec.tynt.com",qb=";Attribution;Attribution Share Alike;Attribution No Derivatives;Attribution Non-Commercial;Attribution Non-Commercial Share Alike;Attribution Non-Commercial No Derivatives".split(";"),rb=" creativecommons.org/licenses/by/3.0 creativecommons.org/licenses/by-sa/3.0 creativecommons.org/licenses/by-nd/3.0 creativecommons.org/licenses/by-nc/3.0 creativecommons.org/licenses/by-nc-sa/3.0 creativecommons.org/licenses/by-nc-nd/3.0".split(" "),
ba=null,sb=function(a){return(a=a.match(/axzz([^?$]*)/))&&2==a.length?a[1]:null},tb=function(a){u(E+"/b/a?g="+a+"&id="+D+"&r="+encodeURIComponent(h.referrer)+"&ts="+Date.now(),function(a){})},Ra=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},ub=function(){var a;ba=!1;if("function"===typeof k.getSelection&&"function"===typeof h.createRange){var b=k.getSelection();if("function"===typeof b.addRange&&"function"===typeof b.removeAllRanges&&"number"===typeof b.rangeCount){var c=
[];for(a=0;a<b.rangeCount;a++)c.push(b.getRangeAt(a));a=h.body.appendChild(h.createElement("div"));a.contentEditable="false";var d=a.appendChild(h.createTextNode("\u00a0\u00a0\u00a0")),f=h.createRange(),e=f.cloneRange();f.setStart(d,0);e.setEnd(d,3);e.setStart(d,2);b.removeAllRanges();b.addRange(f);try{b.addRange(e)}catch(g){}ba=2==b.rangeCount;h.body.removeChild(a);b.removeAllRanges();f.detach();e.detach();for(a=0;a<c.length;a++)b.addRange(c[a])}}},P=!1,vb=function(a){var b,c="";null===ba&&ub();
if(P)return!1;P=!0;var d="";if(g.a){var f=J(a);"undefined"!==typeof trackAttributionView&&(c='<img src="'+n.protocol+E+"/b/l?id="+e.tyntIds()+"&g="+a+'">');a=c+'<a style="color: #003399;" href="';d+=g.ap+" ";g.st&&(d=d+a+f+'">'+Ra(U)+"</a> ");g.su&&(d=d+a+f+'">'+Ra(f)+"</a>");0<g.as.length&&(d=d+"\n<br>"+g.as+" ");0<g.cc&&(d=d+"\n<br>Under Creative Commons License: "+a+n.protocol+rb[g.cc]+'">'+qb[g.cc]+"</a>");if(g.w||g.f)d+="\n<br>Follow us: ",g.w&&(d=d+'<a href="'+n.protocol+Qa+"/b/rw?id="+e.tyntIds()+
"&u="+g.w+'" target="_blank">@'+g.w+" on Twitter</a>"),g.w&&g.f&&(d+=" | "),g.f&&(d=d+'<a href="'+n.protocol+Qa+"/b/rf?id="+e.tyntIds()+"&u="+g.f+'" target="_blank">'+g.f+" on Facebook</a>")}g.el&&(0<d.length&&(d+="\n<br>"),d+=g.el);var l,m;l=r("div",{},{overflow:"hidden",color:"#000000",backgroundColor:"#FFFFFF",textAlign:"left",textDecoration:"none",border:"none"});if(h.selection&&h.selection.createRange){var q=w.scrollLeft||p.scrollLeft,t=w.scrollTop||p.scrollTop;m=r("div",{},{overflow:"hidden",
position:"absolute",left:q+20+"px",top:t+20+"px",width:"1px",height:"1px"});p.insertBefore(m,p.firstChild);var u=h.selection.createRange();l.innerHTML=g.t?d+"<br><br>"+u.htmlText:u.htmlText+"<br><br>"+d;Ha(l);m.appendChild(h.createElement("br"));m.appendChild(l);d=p.createTextRange();d.moveToElementText(l);d.select();setTimeout(function(){p.removeChild(m);""!==u.text&&(u.select(),w.scrollLeft=q,p.scrollLeft=q,w.scrollTop=t,p.scrollTop=t);P=!1},0)}else if(ba)b=k.getSelection(),m=r("div",{},{height:0,
position:"absolute",top:"-1000px"}),m.innerHTML="<br>",g.t?(p.insertBefore(m,p.firstChild),l.innerHTML=d+"<br><br>"):(p.appendChild(m),l.innerHTML="<br>"+d+"<br>"),m.appendChild(l),d=h.createRange(),d.selectNode(l),b.addRange(d),k.setTimeout(function(){m.parentNode.removeChild(m);P=!1},0);else{b=k.getSelection();var v=b.getRangeAt(0),d=r("span",{innerHTML:d});g.t?(d.innerHTML+="<br/><br/>",l.appendChild(d),l.appendChild(v.cloneContents())):(l.appendChild(v.cloneContents()),d.innerHTML="<br/><br/>"+
d.innerHTML,l.appendChild(d));Ha(l);l.style.width=.1;l.style.height=.1;l.style.position="absolute";l.style.top="-1000px";l.style.left="-1001px";l.appendChild(h.createElement("br"));d=l.innerText.length;p.insertBefore(l,p.firstChild);l.innerText.length!=d&&(l.style.overflow="");b.selectAllChildren(l);setTimeout(function(){l.parentNode.removeChild(l);b.removeAllRanges();b.addRange(v);P=!1},0)}return!0},xb=function(a,b,c){c=!0;if(g.a||g.el){var d;d=ka(b);d=2<=d.length?W(d.charAt(0))||W(d.charAt(d.length-
1))||W(d.charAt(d.length/2)):W(d);var f;if(f=g.h)a:{f=(f=wb())?f.className.split(/\s+/):[];for(var e=f.length-1;0<=e;e--)if(void 0!==g.h[f[e]]){f=g.h[f[e]];break a}f=void 0}if(!1!==f&&(d&&b.replace(/\s/g,"").length>=2*g.aw||!d&&T(b)>=g.aw)||f)if(g.a||g.el)c=vb(a.g),g.a&&(a.trace_type=0)}return c},wb=function(){return h.selection&&h.selection.createRange?function(){var a=h.selection.createRange(),b=a.duplicate();b.collapse(!0);return(b=b.parentElement())&&e.trim(a.text)==e.trim(b.innerText)?b:null}:
function(){var a=k.getSelection().getRangeAt(0),b=3==a.startContainer.nodeType?a.startContainer.parentNode:a.startContainer;return b&&e.trim(a.toString())==e.trim(b.textContent)?b:null}}(),yb=function(a){var b=a?864E5:-5E3,b=new Date(Date.now()+b);h.cookie="tracerabg="+a+";path=/;expires="+b.toUTCString()},Ab=function(a){var b;a:{b=h.getElementsByTagName("script");for(var c=0;c<b.length;c++)if(/\/show_afs_search\.js/i.test(b[c].src)){b=!0;break a}b=!1}!b&&zb(k.location)&&(Tynt.b=a||I(k.location.href),
k.location.replace(k.location.href+("#"===k.location.href[k.location.href.length-1]?"":"#")+"axzz"+Tynt.b))},zb=function(a){if(""!==a.hash&&"#"!==a.hash)return!1;if("boolean"==typeof g.ba&&g.ba)g.ba=["/"];else if(!g.ba)return!0;for(var b,c=g.ba.length-1;0<=c;c--){b=null;var d=g.ba[c],e=d.indexOf("/");0!==e&&(b=d.slice(0,e),d=d.slice(e));if(!b||a.host==b)if("#"==d.charAt(d.length-1)){if(0===a.pathname.indexOf(d.slice(0,-1)))return!1}else if(a.pathname==d)return!1}return!0},Bb=function(){h.cookie.match(/ty_attributionBlockedByIp=[tf]/)||
"[object Array]"!==Object.prototype.toString.apply(g.ipb)?v("afterIpBlockCheck",g):pb();0!==Tynt.settings._error||pa()||Tynt.m.push(xb);if(g.b&&!pa()){var a=sb(k.location.href);a?"#axzz"+e.getCookie(h.cookie,"tracerabg")==k.location.hash||Ga()||(tb(a),Ia(2)):(Ab(e.getCookie(h.cookie,"tracerabg")),yb(Tynt.b))}(/tynt-mobile-ss-test/.test(k.location.href)||g.ss&&(X()&&X()&&K("m")||!X()))&&!pa()&&(Tynt.m.push(ib),fa(nb));v("afterDynamicConfig",g);fa(function(){v("afterDynamicConfigAndDocumentLoaded",
g)})};Tynt.cmd.push(function(){g=Tynt.settings.get();Bb()});var Sa=function(){var a=h.title.indexOf("#ixzz");-1<a&&(h.title=h.title.substring(0,a));a=h.title.indexOf("#axzz");-1<a&&(h.title=h.title.substring(0,a))},Q=function(a){if(!a)return{};for(var b={},c=a.substring(a.indexOf("?")+1).split("&"),d=0;d<c.length;d++){var e=c[d].split("=");0===e[0].indexOf("amp;")&&(e[0]=e[0].substring(4));b[e[0]]=e[1]}a=a.split("/");a.pop();b.scriptPathUri=a.join("/");return b}(function(){for(var a=h.getElementsByTagName("script"),
b=0;b<a.length;b++)if(/\/tracer.*\?/i.test(a[b].src))return a[b].src;return null}()),Cb=Q.user||e.getPubId();Q.user&&22==Q.user.length&&!Tynt[Q.user]&&Tynt.push(Q.user);/tracer=test/.test(k.location.href)&&u(ya+"/script/verify/"+Cb);(function(){if(/disableTracer=/.test(k.location.href)){var a=k.location.href.match(/disableTracer=([^?$]*)/)[1],b=new Date;b.setDate(a&&"on"==a?b.getDate()+365:b.getDate()-2);N("disableTracer="+(a&&"on"==a?"y":"n"),"expires="+b.toUTCString());b=r("div",{id:"TyntLocalOptOut"},
{zIndex:"10000",position:"absolute",top:"10%",left:"10%",width:"80%",height:"80%",backgroundColor:"white",color:"black",textAlign:"center",fontSize:"32px",paddingTop:"10%",border:"1px solid gray"});b.innerHTML="Tynt Insight has been turned "+(a&&"on"==a?"off":"on")+" in this browser.<br>You may close this window.";p.insertBefore(b,p.firstChild)}})();if(!Fa()){S&&(Sa(),h.attachEvent("onpropertychange",Sa));var ha=ja();cb();Tynt.settings.download()}if("undefined"===typeof Ta)var Ta=10;(new Date).getDate()===
Ta&&function(){var a=h.createElement("script"),b=h.getElementsByTagName("script")[0];a.async="async";a.type="text/javascript";a.src=n.protocol+Wa+"/cb.js";b.parentNode.insertBefore(a,b)}();var qa=null,ra=0,sa=function(){"object"==typeof h.body.oncopy&&null!==h.body.oncopy?(h.body.oncopy=null,x(13)):setTimeout(sa,2E3)},Db=function(){"undefined"===typeof stlib||"undefined"===typeof stlib.hash||"undefined"===typeof stlib.hash.doNotCopy||stlib.hash.doNotCopy||(sa(),setTimeout(function(){clearInterval(qa)},
2E3));ra+=1;5<=ra&&clearInterval(qa)};t.afterDynamicConfigAndDocumentLoaded.push(function(){if("undefined"===typeof stlib||"undefined"===typeof stlib.hash||"undefined"===typeof stlib.hash.doNotCopy||stlib.hash.doNotCopy){for(var a=!1,b=h.getElementsByTagName("script"),c=0;c<b.length;c++)if(b[c].getAttribute("src")&&/sharethis/.test(b[c].src)){a=!0;break}a&&(qa=setInterval(Db,2E3))}else sa();"function"===typeof v&&v("afterProtectTynt")})}else setTimeout(function(){Tynt.TIL()},50)};Tynt.TIL()}();
