window.__iasPET=window.__iasPET||{};
window.__iasPET.start=window.__iasPET.start||function(g,w){var h;try{var n=function(a){var c,d,e,f={},b=function(a){return a&&a.replace(/[^\w-_.>\/]/g,"")};c=b(function(a){return a&&a.replace(/\//g,"")}(a.adSlotId));d=a.size&&a.size instanceof Array&&a.size.join(".");e=b(a.adUnitPath);f.id=c;f=k.extend(f,function(a){var b={};k.isArray(a)&&(a.every(k.isArray)?(a=a.map(function(a){return a.join(".")}).join(","),b.ss="["+a+"]"):b.s=a.join("."));return b}(a.size));f.p=e;return{toString:function(){var a,
b=[];for(a in f)b.push(a+":"+f[a]);return"slot="+("{"+b.join(",")+"}")},isValid:function(){return c&&d&&e}}},x=function(){var a={},c=function(b){return setTimeout(function(){a[b]||(h.diagPix(l.LONG_REQUEST,{message:"threshold:2000"}),h.warn("Long PET request that exceeds 2000ms."))},2E3)},d=function(b){var f=k.getQueryParamByName("iasprofileprobability")||10,d,c,e={};k.chance(f)&&setTimeout(function(){c=(d=a[b])&&d-b;e.responsetime=c;e.probability=f;h.diagPix(l.PROFILE_RESPONSE,{message:k.buildQueryString(e,
":")})},2E3)},e=function(a){return a.width+"."+a.height},f=function(){var a=[],f=g.__iasPET.pubId,d=e(r.getWindowSize(g)),c=e(r.getScreenSize(g)),k=g.__iasPET.sessionId;if(!m.isEmpty()&&f)return a.push("anId="+f),a.push(m),a.push("wr="+d),a.push("sr="+c),a.push("sessionId="+k),h.log("ad slots set: "+m),h.log("anid set: "+f),a.join("&");m.isEmpty()&&h.error("Expected valid ad slot configuration.");f||h.error("Expecting valid IAS publisher id.");h.diagPix(l.MISSING_DATA)};return{send:function(b,e){var q,
g,t=!1,l,p=k.getQueryParamByName("iasendpoint")||"//pixel.adsafeprotected.com/services/pub",n=f(),r=k.isFn(b);n&&(q=function(f){t=k.now();h.log("PET response "+f);a[g]=t;u.updateData(f);r&&b(f);clearTimeout(l)},g=k.now(),a[g]=!1,k.sendXHR(p,n,q,e),l=c(g),d(g),m.clear())}}},v=function(){var a,c,d,e,f=function(b){b&&(c=k.isFn(b.dataHandler)?b.dataHandler:c,a=b.timeout||a,m.setAdSlots(b))};return{setup:function(){d=new x;e=e||g.__iasPET.queue;e.push=function(b){var e;try{if(k.isFn(b))e=b();else if(k.isObj(b))e=
b;else throw Error("Items pushed into the queue must be a function or object");}catch(g){h.error("Error processing queued command: "+g.message)}f(e);d.send(c,a)}},executeCommands:function(){var b,s;if((e=e||g.__iasPET.queue)&&e.length){for(b=0;b<e.length;++b){try{k.isFn(e[b])?s=e[b]():k.isObj(e[b])&&(s=e[b])}catch(q){h.error("Error processing queued command: "+q.message)}f(s)}d.send(c,a)}}}}(),m=function(){var a=[],c=function(d){(new n(d)).isValid()?a.push(new n(d)):h.error("Missing ad slot id, slot size and/or ad unit path.")};
return{setAdSlots:function(a){(a=a.adSlots)&&(a instanceof Array?a.forEach(function(a){c(a)}):k.isObj(a)&&c(a))},clear:function(){a=[]},isEmpty:function(){return 0===a.length},toString:function(){return a.join("&")}}}(),u=function(){var a={},c={},d=function(a,b){a&&k.isFn(a.setTargeting)&&k.forIn(b,function(b,c){h.log("setting targeting: {"+b+": "+c+"}");a.setTargeting(b,c)})},e=function(){var a,b=g.googletag.pubads().getSlots();b?b.forEach(function(b){(a=k.isFn(b.getSlotElementId)&&b.getSlotElementId())&&
d(b,c[a])}):h.error("GPT slots have to be defined before setting slot level keyword targeting")};return{updateData:function(f){var b=JSON.parse(f);f=b.brandSafety;var d=b.slots;a.fr=b.fr;b=function(a,b){k.forIn(a,function(a,f){b[a]=f})};b(f,a);b(d,c)},setTargeting:function(){g.googletag?g.googletag.cmd.push(function(){d(g.googletag.pubads(),a);e()}):(h.error("googletag is not available. Cannot set keyword targeting for GPT."),h.diagPix(l.GPT_NA));k.isEmptyObj(a)&&h.warn("PET page level data (brand safety, fraud) is not available yet.");
k.isEmptyObj(c)&&h.warn("PET slot level data (viewability) is not available yet.")}}}(),l={GPT_NA:"gpt",LONG_REQUEST:"longreq",MISSING_DATA:"m",XHR_NA:"na",PROFILE_RESPONSE:"profile",XHR_GENERAL:"x",XHR_ERROR:"xe",XHR_TIMEOUT:"xt"},r={getWindowSize:function(a){return{width:a.innerWidth||-1,height:a.innerHeight||-1}},getScreenSize:function(a){return{width:a.screen&&a.screen.width||-1,height:a.screen&&a.screen.height||-1}}};g.__iasPET.queue=g.__iasPET.queue||[];g.__iasPET.VERSION="1.7.0";g.__iasPET.setTargetingForGPT=
u.setTargeting;var p=function(){var a=function(a){top.postMessage(a,"*")};return g.postMessage?a:function(){}}();h=function(){var a={},c=function(a,b){var c="background-color: ",d=g.console&&"function"===typeof g.console.error,e=k.getQueryParamByName("iasdebug"),e=e&&"TRUE"===e.toUpperCase();"log"===a?c+="lightgreen":"error"===a?c+="pink":"warn"===a&&(c+="lightyellow");d&&e&&(console.log("%cIAS_DEBUG: "+b,c),p("DEBUG_petErrorsLog: IAS_DEBUG: "+b))},d=c.bind(null,"log"),e=c.bind(null,"warn");return{diagPix:function(c,
b){var d,e,h,l;if(!a[c])try{d=g.__iasPET.pubId||"",e=g.__iasPET.sessionId||"",a[c]=!0,h={code:"pet_"+c,anid:d,sessionId:e},b&&(h.err=encodeURIComponent(b.message)),l=k.buildQueryString(h,":"),(new Image).src="//pixel.adsafeprotected.com/jsdiagnostic?"+l,p("DEBUG_petErrorsReport: //pixel.adsafeprotected.com/jsdiagnostic?"+l)}catch(m){}},error:c.bind(null,"error"),log:d,warn:e}}();var k={buildQueryString:function(a,c){var d="";a&&(d=Object.keys(a).reduce(function(d,f){d.push([f,a[f]].join(c));return d},
[]).join("&"));return d},getQueryParamByName:function(a){var c,d=g.location.search&&g.location.search.toLowerCase();a=d&&d.indexOf(a);-1!==a&&(c=d.indexOf("=",a)+1,a=d.indexOf("&",c),a=-1===a?w:a,c=decodeURIComponent(d.slice(c,a)));return c},sendXHR:function(a,c,d,e){var f,b;try{if(f=new XMLHttpRequest)b=encodeURI(a+"?"+c),f.open("GET",b),p("DEBUG_petDataRequest: "+b),f.onreadystatechange=function(){var a,b;if(4===f.readyState&&200===f.status)if(a=f.responseText,b=a.code)h.error("XMLHttpRequest failure code: "+
a.code+", message: "+a.message);else if(d)try{d.call({},a)}catch(c){h.error("Error firing the XMLHttpRequest callback: "+c.message)}},e&&(f.timeout=e),f.ontimeout=function(){h.error("XMLHttpRequest timeout event is fired.");h.diagPix(l.XHR_TIMEOUT,{message:"timeout:"+e})},f.onerror=function(a){h.error("XMLHttpRequest error event is fired.");h.diagPix(l.XHR_ERROR,a)},f.send()}catch(g){h.error("Error sending XMLHttpRequest: "+g.message),h.diagPix(l.XHR_GENERAL,g)}},forIn:function(a,c){for(var d in a)a.hasOwnProperty(d)&&
c(d,a[d])},getUID:function(){var a=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)};return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()},extend:function(a,c){c&&Object.keys(c).forEach(function(d){a[d]=c[d]});return a},isArray:function(a){return a instanceof Array},isDef:function(a){return"undefined"!==typeof a},isFn:function(a){return"function"===typeof a},isObj:function(a){return"object"===typeof a},isEmptyObj:function(a){return 0===Object.getOwnPropertyNames(a).length},
now:function(){return(new Date).getTime()},chance:function(a){return 100*Math.random()<a}};"undefined"===typeof XMLHttpRequest?h.diagPix(l.XHR_NA):(g.__iasPET.sessionId=k.getUID(),v.setup(),v.executeCommands())}catch(y){h.error(y.message)}};window.__iasPET.start(window);
