window.SPR=function(){function z(a,d){var c=this;c.H=[];c.B=a||{};c.Pc=b.wc;c.ra=!1;c.oc=d||b.$b;p.Vb(c.oc);g.a(a[b.sa]);a[b.c]=a[b.c]||q.current[b.c];a[b.url]=a[b.url]||e.ka();a[b.title]||(a[b.title]=e.ja(a[b.url]));if(a[b.url])c.a=function(){if(c.kc())return c.Rb(),c;g[b.error](c.zb());return null},c[b.zc]=function(a){c.lc(a)?c.Sb(a):c.wb(a);return c},c[b.rc]=function(a){c.ic(a)?c.Qb(a):c.vb();return c},c[b.Ec]=function(a){c.mc(a)?c.Tb(a):c.xb();return c},c[b.pc]=function(){c.ra||(c.m(c.ga(c.ga())),
c[b.Ga](100),c.ra=!0);return c},c[b.Ga]=function(a){if(f.contains(c.H,a))return null;if(f.contains(f.V,a)){var d=c.g();d[b.i]=b.Ha;d[b.Ha]=c.ab(a);c.m(d)}else g[b.error](b.ib);return c},c.ab=function(a){var d,n=f.V,e={};if(!f.contains(n,a))g[b.error](b.ua);else if(!f.contains(c.H,a))for(d=0;d<n.length;d+=1){var l=n[d];a>=l&&!f.contains(c.H,l)&&(c.H.push(l),e[l]=!0,g[b.info](b.Ba+l))}return e},c.m=function(a){p.f(b.h,b.tc,a)},c.Rb=function(){c.m(c.gb())},c.Sc=function(){return q.current},c.g=function(){return v.da(c.B)},
c.gb=function(){var a=c.g();a[b.i]=b.vc;return a},c.kc=function(){var a;for(a=0;a<r.length;a+=1)if(!c.B[r[a]])return!1;return!0},c.zb=function(){var a,d=[];for(a=0;a<r.length;a+=1)c.B[r[a]]||d.push(r[a]);return b.kb+d.join(", ")},c.Sb=function(a){c.m(c.cc(a))},c.lc=function(a){return a===b.Cc||a===b.Dc},c.cc=function(a){var d=c.g();d[b.i]=b.Ac;d[b.Bc]=a;return d},c.wb=function(a){if(a)g[b.error](a+b.lb);else g[b.error](b.gc)},c.ga=function(){var a=c.g();a[b.i]=b.qc;return a},c.Qb=function(a){c.m(c.Ya(a))},
c.Ya=function(a){var d=c.g();d[b.i]=b.sc;d[b.xc]=a;return d},c.ic=function(a){return!isNaN(a)},c.vb=function(){g[b.error](b.hb)},c.Tb=function(a){c.m(c.dc(a))},c.dc=function(a){var d=c.g();d[b.i]=b.Fc;d[b.yc]=a;return d},c.mc=function(a){return!isNaN(a)&&c.nc(a)},c.nc=function(a){return f.Qa(f.Gc,a)},c.xb=function(){g[b.error](b.jb)};else g[b.error](b.Y+b.la)}var b={h:"edge.simplereach.com",version:"3",Oa:"d8rk54i4mohrb.cloudfront.net",fb:"/n",ec:"/t",tc:"/v",ma:"/event",Ma:"/pixel?bad=true&error=",Nc:"/iframe.html",
Pa:"/container.html",Ca:"000000000000000000000000",Y:"SPR-ERROR: ",la:"100 - Missing url",Ib:"__reach_config",Na:"cache_buster",za:"__srret",Fa:"__srui",K:"0",Cb:"1",eb:"img",Db:"1px",width:"width",aa:"undefined",error:"error",Ab:"off",info:"info",F:"SPR_DEBUG",ac:"//",Z:"string",referrer:"referrer",uid:"uid",s:"callback",f:"jsonp",url:"url",title:"title",c:"pid",ta:"ignore_metadata",Aa:"s",r:"r",t:"t",e:"e",x:"x",n:"n",hc:"v",sa:"ignore_errors",Hb:"preview",L:"authors",N:"channels",$:"tags",w:"date",
Oc:"inframe",La:"ajax",Mc:"iframe",Sa:"custom_tracking",Jb:"reach_tracking",l:"ref_url",U:"page_url",Xc:"user_id",yb:"manual_scroll_depth",ia:"content_height",Rc:"rd",Lc:"fb",Hc:"de",sb:"li",Eb:"pi",Ra:"csd",tb:"www.linkedin.com",Fb:"partners-api.pinterest.com",ub:"/countserv/count/share",Gb:"/v1/urls/count.json",ua:"[error] Invalid amount please send scroll depths of only: 25, 50, 75 or 100",Ba:"[info] sending scrollDepth of: ",Pb:"[info] scroll depth not activated, not sending data",$b:"SimplereachVideo",
i:"event_name",kb:"Missing params please provide a ",lb:" is not a valid start event type.",gc:"Cannot have an undefined start type. Please provide a start type.",hb:"Please pass a valid number",ib:"[error] Invalid quartile please send quartiles of only: 25, 50, 75 or 100",Tc:"[error] Quartile for this video already sent",jb:"Please pass a valid threshold number",uc:"video_id",rb:"length",description:"description",Wc:"thumbnail_url",Uc:"source_url",xa:"networks",wc:"video",zc:"start",rc:"elapsed",
pc:"complete",Ga:"quartile",Ec:"elapsedThreshold",vc:"init",Ac:"start",sc:"elapsed",Ha:"quartile",qc:"complete",Fc:"elapsed_threshold",Bc:"start_type",Cc:"auto",Dc:"click",xc:"seconds_elapsed",yc:"threshold"},f={Nb:function(){return Math.random().toString(36).replace(/[^a-z]+/g,"")},returnValue:function(a){return a},S:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},log:function(a){window.console&&console.log(a)},nb:function(a){return"[object String]"===
Object.prototype.toString.call(a)},J:function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b},wa:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a},contains:function(a,b){return-1!==(a.join(",")+",").indexOf(b+",")},Qa:function(a,b){if(!isNaN(b)&&!this.nb(b))for(var c=0;c<=a.length;c++)if(a[c]===b)return!0;return!1},P:function(a){typeof a===b.Z&&(a=a.split(","));if(this.S(a)){for(var d=0;d<a.length;d+=1)typeof a[d]===b.Z&&(a[d]=a[d].replace(/^\s*/,"").replace(/\s*$/,
"").replace(/\|/,""));return a.join("|")}},A:function(){},oa:function(){return window.location.protocol+"//"},V:[25,50,75,100],Gc:[3,15,30,45]},t={encode:function(a,b){var c=[];if(f.S(a))for(var d=0,h;d<a.length;d+=1)h=a[d],/\[\]$/.test(b)?c.push(encodeURIComponent(b)+"="+encodeURIComponent(h)):c.push(this.encode(h,b+"["+("object"===typeof h?d:"")+"]"));else if("object"!==typeof a||null===a||"nodeType"in a)c.push(encodeURIComponent(b)+"="+encodeURIComponent(a));else for(d in a)Object.prototype.hasOwnProperty.call(a,
d)&&(b?c.push(this.encode(a[d],b+"["+d+"]")):c.push(this.encode(a[d],d)));return c.join("&")},decode:function(a){var d={},c=0,n={"true":!0,"false":!1,"null":null};for(a=a.replace(/\+/g," ").split("&");c<a.length;c+=1){var h=a[c].split("="),e=decodeURIComponent(h[0]),g=d,l=0,m=e.split("]["),k=m.length-1;/\[/.test(m[0])&&/\]$/.test(m[k])?(m[k]=m[k].replace(/\]$/,""),m=m.shift().split("[").concat(m),k=m.length-1):k=0;if(2===h.length)if(h=(h=decodeURIComponent(h[1]))&&!isNaN(h)?+h:h===b.aa?void 0:void 0!==
n[h]?n[h]:h,k)for(;l<=k;l+=1)e=""===m[l]?g.length:m[l],g=g[e]=l<k?g[e]||(m[l+1]&&isNaN(m[l+1])?{}:[]):h;else f.S(d[e])?d[e].push(h):d[e]=void 0!==d[e]?[d[e],h]:h;else e&&(d[e]=void 0)}return d}},u={ya:{},qa:function(a){var b=document.cookie||"",c=this.ya[a];c||(c=a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),c=new RegExp("(?:^|;)\\s?"+c+"=(.*?)(?:;|$)","i"),this.ya[a]=c);return(a=b.match(c))&&decodeURIComponent(a[1])},X:function(a,b,c){var d="";c&&(d="; expires="+c.toGMTString());document.cookie=
a+"="+b+d+"; path=/"},Ic:function(a){this.X(a,"",new Date(1982,5,13))}},q={current:{}},g={na:!1,info:f.A,error:f.log,a:function(){window[b.F]&&(this.na=!0,window[b.F][b.info]&&(this[b.info]=window[b.F][b.info]),window[b.F][b.error]&&(this[b.error]=window[b.F][b.error]))},reset:function(){this.na=!1;this[b.info]=f.A;this[b.info]=f.log},Xb:function(a){var d=document.createElement(b.eb);d.src=f.oa()+b.h+b.Ma+a.message;d.setAttribute(b.width,b.Db);document.body?document.body.appendChild(d):document.head.appendChild(d)},
Yb:function(a){a===b.info?(this[b.info]=f.log,this[b.error]=f.log):a===b.error?(this[b.info]=f.A,this[b.error]=f.log):(this[b.info]=f.A,this[b.error]=f.A)}},e={K:0,v:{x:0,y:0},R:!0,a:function(){function a(){e.R=document[h]?!1:!0}function b(){e.flush();window.removeEventListener("DOMContentLoaded",b,!1)}function c(){/loaded|interactive|complete/.test(document.readyState)&&(document.detachEvent("onreadystatechange",c),g&&(g=!1,e.flush()))}var e=this;e.K=0;this.Bb(window,"mousemove",function(a){e.v=
{x:a.clientX,y:a.clientY}});if("undefined"!==typeof document.hidden){var h="hidden";var f="visibilitychange"}else"undefined"!==typeof document.mozHidden?(h="mozHidden",f="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(h="msHidden",f="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(h="webkitHidden",f="webkitvisibilitychange");"undefined"!==typeof document.addEventListener&&"undefined"!==typeof h&&document.addEventListener(f,a,!1);var g=!0;window.addEventListener?window.addEventListener("DOMContentLoaded",
b,!1):document.attachEvent&&document.attachEvent("onreadystatechange",c)},Ia:function(a,b){var c=document.createElement("iframe"),d=document.body;c.setAttribute("name","spr");c.src=a;c.setAttribute("height","1");c.setAttribute("width","1");c.setAttribute("visible","false");c.setAttribute("id","spr-iframe-"+b);c.style.display="none";d||(d=this.b("BODY")[0]);d||(d=this.b("HEAD")[0]);g.info(a);d.appendChild(c);return c},Ua:function(){for(var a=this.b("meta"),b=0;b<a.length;b+=1)if("og:url"===a[b].getAttribute("property"))return a[b].content;
return!1},Ta:function(){for(var a=this.b("link"),b=0;b<a.length;b+=1)if("canonical"===a[b].rel)return a[b].href;return!1},Va:function(){for(var a=this.b("meta"),b=0;b<a.length;b+=1)if("twitter:url"===a[b].getAttribute("name"))return a[b].content;return!1},Wa:function(){return window.location.protocol+"//"+window.location.hostname+window.location.pathname},ka:function(){return this.Ta()||this.Ua()||this.Va()||this.Wa()},pa:function(){return document.referrer},ja:function(a){for(var b=this.b("meta"),
c=0;c<b.length;c+=1)if("og:title"===b[c].getAttribute("property")||"twitter:title"===b[c].getAttribute("name"))return b[c].content;return document.title||a||!1},Kb:function(a){var b=document.body,c=this.b("BODY")[0],e=this.b("HEAD")[0];b&&b.contains(a)?b.removeChild(a):c&&c.contains(a)?c.removeChild(a):e&&e.contains(a)&&e.removeChild(a);return a},Ja:function(a){var b=this,c=document.createElement("script");c.type="text/javascript";c.setAttribute("async",!0);c.setAttribute("name","spr");c.setAttribute("id",
"spr-script");c.src=a;g.info(a);this.T(function(){setTimeout(function(){b.b("HEAD")[0].appendChild(c)},1)});return c},j:[],ready:/loaded|interactive|complete/.test(document.readyState),flush:function(){var a=this.j.shift();for(this.ready=!0;a;)a(),a=this.j.shift()},T:function(a){this.ready?(this.j.push(a),this.flush()):document.documentElement.doScroll?window.self===window.top?function c(){if(!document.uniqueID&&document.expando)return this.j.push(a);try{document.documentElement.doScroll("left"),
a()}catch(n){setTimeout(c,0)}}():this.j.push(a):this.j.push(a)},Bb:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c);return a},Ab:function(a,b,c){a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},I:function(){return(window.pageYOffset?window.pageYOffset:document.documentElement?document.documentElement.scrollTop:0)-this.K},b:function(a){var b=[],c=0,e;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(document.getElementById(a.substring(1)));
break;case ".":var f=document.getElementsByTagName("*");for(e=" "+a.substring(1)+" ";c<f.length;c+=1)a=(" "+f[c].className+" ").replace(/[\n\t\r]/g," "),-1<a.indexOf(e)&&b.push(f[c]);break;default:b=document.getElementsByTagName(a)}return b}},v={da:function(a){var d;var c=f.J(a);c[b.L]&&(c[b.L]=f.P(c[b.L]));c[b.N]&&(c[b.N]=f.P(c[b.N]));c[b.$]&&(c[b.$]=f.P(c[b.$]));c[b.w]&&typeof c[b.w]!==b.Z&&(c[b.w]=c[b.w].toString());c[b.referrer]=""==c[b.l]?"":this.W(c[b.referrer]);c[b.l]=this.W(c[b.l]);c[b.U]=
c[b.U]||window.location.toString();c[b.uid]?c[b.uid]=c[b.uid]:(d=this.cb())&&(c[b.uid]=d);c[b.url]&&(c[b.url]=this.Ob(c[b.url]),a[b.url]=c[b.url]);return c},W:function(a){""!==a&&(a=a||e.pa());return a},cb:function(){return u.qa(b.Fa)},Ob:function(a){if(0===a.indexOf("http%253A")||0===a.indexOf("https%253A"))a=decodeURIComponent(a);if(0===a.indexOf("http%3")||0===a.indexOf("https%3"))a=decodeURIComponent(a);return a}},p={callbacks:{},M:"SPR",Vb:function(a){this.M=a},f:function(a,d,c,g,h){g=g||function(){};
h||(h="cb");var k="cb"+f.Nb(),n=this;c[h]=this.M+".API.callbacks."+k;h=f.oa();"file://"===h&&(h="http://");c[b.hc]=b.version;c=t.encode(c);var l=e.Ja(h+a+d+"?"+c);n.callbacks[k]=function(a){setTimeout(function(){l.parentNode&&l.parentNode.removeChild(l)},0);g(a);try{delete n.callbacks[k]}catch(D){n.callbacks[k]=null}}}},w={Qc:!1,Kc:!0,o:0,Da:5E3,fc:12E5,interval:null,reset:function(){e.K=e.I();window.clearInterval(this.interval)},track:function(a){var d=this,c;d.interval=setInterval(function(){e.R&&
(d.o+=d.Da);d.Ea()&&(d.o=0);c=f.J(a);c[b.t]=d.o;c[b.e]=d.mb()?5E3:0;c[b.Aa]=e.I();0===c[b.c]&&(c[b.c]=b.Ca);e.R&&!d.Ea()&&d.jc(c)&&0<c[b.e]&&(d.o=0,p.f(b.h,b.ec,c));d.pb=e.v.x;d.qb=e.v.y;d.ob=e.I()},d.Da)},mb:function(){return!0!==this.Za?this.Za=!0:this.pb!==e.v.x||this.qb!==e.v.y||this.ob!==e.I()?!0:!1},Ea:function(){return this.o>=this.fc},jc:function(a){return a[b.url]&&a[b.c]}},k=f.V,y={G:[],data:{},response:null,options:null,Vc:!1,a:function(a,d){this.reset();this.options=d;this.response=a;
var c=this;e.T(function(){c.height=c.$a();c.D||(c.D=function(){c.ea()});q.current[b.yb]?c.Lb():c.Ka()})},Ka:function(){typeof document.addEventListener!==b.aa?document.addEventListener("scroll",this.D,!1):window.attachEvent("onscroll",this.D);this.ea()},Lb:function(){typeof document.removeEventListener!==b.aa?document.removeEventListener("scroll",this.D,!1):window.detachEvent("onscroll",this.D)},ea:function(){var a=this.bb()+Math.min(document.documentElement.clientHeight,window.innerHeight||0),b=
0;a>=this.height?b=k[3]:b=a/this.height*100;97<=b?this.C(k[3]):b>=k[2]?this.C(k[2]):b>=k[1]?this.C(k[1]):b>=k[0]&&this.C(k[0])},$a:function(){if(q.current[b.ia])var a=q.current[b.ia];else{a=document.body;var d=document.documentElement;a=Math.max(a.scrollHeight,a.offsetHeight,d.clientHeight,d.scrollHeight,d.offsetHeight)}return a},bb:function(){var a="CSS1Compat"===(document.compatMode||"");return void 0!==window.pageYOffset?window.pageYOffset:a?document.documentElement.scrollTop:document.body.scrollTop},
C:function(a){this.data={};if(!f.contains(k,a))g[b.error](b.ua);else if(!f.contains(this.G,a))if(this.Wb(a),this.response[b.Ra])this.Ub();else g[b.info](b.Pb)},Wb:function(a){var d;for(d=0;d<k.length;d+=1){var c=k[d];a>=c&&!f.contains(this.G,c)&&(this.G.push(c),this.data[c]=!0,g[b.info](b.Ba+c))}},B:function(){return f.wa({event:"csd",sd:this.data},this.options)},Ub:function(){if(!this.response.error){var a=this.B();p.f(b.h,b.ma,a)}},reset:function(){this.G=[]}},A={xa:[{name:b.sb,ba:b.tb,ca:b.ub,
s:b.s},{name:b.Eb,ba:b.Fb,ca:b.Gb,s:b.s}],Mb:function(a,b){return{url:b}},bc:function(a,d){return function(c){c={event:b.Aa,url:a.url,cid:a.id,pid:a.pid,sn:a.name,data:c};f.wa(c,d);p.f(b.h,b.ma,c)}},u:function(a,b){for(var c=this.xa,d,e=0;e<c.length;e+=1){d=c[e];var g=f.J(a);g.name=d.name;a[d.name]&&p.f(d.ba,d.ca,this.Mb(d.name,g.url),this.bc(g,b),d.s)}}},B={track:function(a){var d=this;0===a[b.c]&&(a[b.c]=b.Ca);p.f(b.h,b.fb,a,function(c){y.a(c,a);if(c.error)g[b.error](b.Y+c.error.code+" - "+c.error.message);
else c.uid&&d.Zb(c.uid),A.u(c,a)})},Zb:function(a){u.X(b.Fa,a,new Date(2042,5,13))}},x={Jc:{},O:{},fa:!1,a:function(){try{e.a();var a=window[b.Ib];u.qa(b.za)?this.va=!0:this.va=!1;u.X(b.za,b.Cb,new Date(2042,5,13));this.u(a)}catch(d){e.T(function(){g.Xb(d)})}},u:function(a){if(a){var d;q.current=a;this.O=f.J(q.current);this.O[b.r]=this.va;(d=this.O[b.La]&&this.fa)||(a[b.url]=a[b.url]||e.ka());if(a[b.url])g.a(a[b.sa]),d&&(a.hasOwnProperty(b.ta)||(a[b.ta]=!0),a[b.U]=a[b.l]=a[b.referrer]=a.url),a[b.title]||
(a[b.title]=e.ja(a[b.url])),w.reset(),d=v.da(a),d[b.Hb]||(!1!==a[b.Jb]&&(B.track(d),w.track(d)),!1!==a[b.Sa]&&this.Xa(d)),this.fa=!0;else g[b.error](b.Y+b.la)}else g[b.error]("Params not passed to collect")},Xa:function(a){a[b.referrer]=a[b.referrer]||e.pa();a[b.l]=v.W(a[b.l]);a[b.Na]=(new Date).getTime();a=t.encode(a);this.ha&&e.Kb(this.ha);this.ha=e.Ia(b.ac+b.Oa+b.Pa+"?"+a,b.x)}},r=[b.c,b.uc,b.rb,b.w],C={create:function(a,b){return new z(a,b)},a:function(a,b){return this.create(a,b).a()}};return{Reach:{collect:function(a){x.u(a)}},
QS:{decode:t.decode},debug:g,setLogLevel:function(a){g.Yb(a)},API:p,collect:function(a){x.u(a)},decode:t.decode,init:function(){x.a()},iframeCollect:function(){},stop:function(){w.reset()},scrollDepthReached:function(a){y.C(a)},video:function(a){return C.a(a,p.M)}}}();window.SPR.init();
