var _tmr=_tmr||[];
(function(){function w(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}function B(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)}function Z(a){for(var b="",c,d=0;d<a;d++)c=16*Math.random()|0,b+=c.toString(16);return b}function r(){return(new Date).getTime()}function ua(){var a="tmr"+(""+Math.random()).slice(2);try{return G.setItem(a,a),G.removeItem(a),!0}catch(b){return!1}}function S(a){try{return G.getItem($+"_"+
a)}catch(b){}return null}function C(a,b){try{G.setItem($+"_"+a,b)}catch(c){}}function aa(a){g(k(a,!0,!1,!1)+";e="+escape("detect"))}function f(){}function H(a){a&&"object"===typeof a&&(!s&&"id"in a)&&(s=a.id)}function ba(a){return a||"https:"==document.location.protocol||"chrome-extension:"==document.location.protocol?"https:":"http:"}function va(a){return(a=!D?void 0:D[a])&&T?a-T:void 0}function g(a){var b=ba(E)+"//top-fwz1.mail.ru"+a;"function"===typeof navigator.sendBeacon&&!0===navigator.sendBeacon(b)||
(a=new Image,a.src=b)}function I(a,b,c){if(!(b&&"object"===typeof b))return l&&console.warn("[TopMailRu]: Invalid event of "+a),null;var d={name:a,title:c.title||null};"id"in c&&!1!==c.id&&(d.id="id"in b&&b.id,!0!==c.id&&(d.id=d.id||c.id));if(l){var e=ca(b,{params:c.required,fn:c.fn});if(e.missed.length)return console.warn("[TopMailRu]"+(d.id?"["+d.id+"]":"")+": Unspecified "+(1<e.missed.length&&e.missed.slice(0,-1).join(", ")+" and "||"")+e.missed.slice(-1)+" in "+a),null;var da=ca(b,{params:c.optional,
fn:c.fn}),f=[].concat(e.values).concat(da.values),e=[].concat(e.missed).concat(da.missed);c.value&&(b="value"in b&&b.value,!0!==c.value&&(b=b||c.value),b?f.push("value: "+b):e.push("value"));d.value=f.length?"{ "+f.join(", ")+" }":"";d.empty=e.length?"("+(1<e.length?e.slice(0,-1).join(", ")+" and "+e.slice(-1)+" are":e.slice(-1)+" is")+" empty)":""}return"id"in c&&!1!==c.id&&!d.id?(l&&console.warn("[TopMailRu]: Undefined counter ID of "+a+" "+d.value),null):d}function ca(a,b){var c=[],d=[],e,f;if(b.params)for(e in b.params)b.params.hasOwnProperty(e)&&
!1!==b.params[e]&&(f=e in a&&a[e],!0!==b.params[e]&&(f=f||b.params[e]),f?c.push(e+': "'+(b.fn?b.fn.call(self,e,f):f)+'"'):d&&d.push(e));return{values:c,missed:d}}function J(a){console.info("[TopMailRu]["+a.id+"]: "+(a.title||a.name)+" "+a.value+" "+a.empty)}function k(a,b,c,d){t&&C(K,++q);var e="id"in a?a.id:s,f="url"in a?a.url:location.href,h="referrer"in a?a.referrer:document.referrer,l="title"in a?a.title:document.title,g;g=U;null===g&&(g=wa());g=null!==g?g?1:0:null;var m="userid"in a?a.userid:
y||0===y?y:void 0,k;k=[];s&&e!==s&&k.push("sec");k=k.join(",");var n;b=(b?"/tracker":"/counter")+"?js=13"+(e?";id="+escape(e):"")+(f?";u="+escape(f):"")+(h?";r="+escape(h):"")+("start"in a&&0<a.start?";st="+escape(a.start):"")+("gender"in a?";gender="+escape(a.gender):"")+("age"in a?";age="+escape(a.age):"")+("pid"in a?";pid="+escape(a.pid):"")+(void 0!==m?";userid="+escape(m):"")+(d&&l?";title="+encodeURIComponent(l):"")+((n=window.screen)?";s="+n.width+"*"+n.height:"")+";vp=";d=n=0;document.documentElement&&
(document.documentElement.clientWidth||document.documentElement.clientHeight)?(n=document.documentElement.clientWidth,d=document.documentElement.clientHeight):"number"==typeof window.innerWidth&&(n=window.innerWidth,d=window.innerHeight);n=b+(""+n+"*"+d)+";touch="+xa+";hds="+ya+";flash="+V+";sid="+ea+";ver="+fa;if(c){if(!D||!W)c="";else{c=[];c.push(W.type);c.push(W.redirectCount);c.push(T);for(b=0;b<ga.length;b++)c.push(va(ga[b]));c=c.join("/")}c=";nt="+c}else c="";c=n+c+("device"in a?";device="+
escape(a.device):"");var p;if("params"in a){n=escape;if(a=a.params)if(b=typeof a,"number"===b||"boolean"===b||"string"===b||a.nodeType||a===a.window)p="";else{d=[];for(p in a)if(a.hasOwnProperty(p)){e=a[p];b=typeof e;if("string"===b)e='"'+e.replace(/[\"\']/g,"\\$&")+'"';else if(!("number"===b||"boolean"===b))continue;d.push('"'+p+'":'+e)}p=!d.length?"":"{"+d.join(",")+"}"}else p="";p=";params="+n(p)}else p="";return c+p+(null!==g?";detect="+g:"")+(t?";lvid="+escape(t?""+L+":"+r()+":"+q+":"+M:""):
"")+(k?";opts="+escape(k):"")+";_="+Math.random()}function ha(a,b){return"/tracker?js=13;id="+a[0]+";e="+escape(b)+";sid="+ea+";ids="+a.join()+";ver="+fa+";_="+Math.random()}function ia(a){for(var b=0;b<u.length;b++)g(k(u[b],!0,!1,!0)+";e="+escape("PVT/"+a))}function za(){U=!0;ja(1);if(!ka&&!F){F=!0;for(var a=0;a<u.length;a++)aa(u[a])}}function Aa(){ja(0);U=!1}function wa(){var a;a=(a=la.cookie.match(RegExp("(?:^|; )"+ma.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):
null;if(null===a)return null;a=a.split("|");if(2!==a.length)return null;var b=a[1],b=r()-b;if(0>b||b>na)return null;a=parseInt(a[0],10);return isNaN(a)?null:a}function ja(a){var b=r(),b=[a,b].join("|"),c=ma;a={path:"/",expires:na};var d=a.expires;"number"===typeof a.expires&&(d=new Date,d.setTime(d.getTime()+a.expires));d&&d.toUTCString&&(d=d.toUTCString());a.expires=d;var b=c+"="+encodeURIComponent(b),e;for(e in a)b+="; "+e,c=a[e],!0!==c&&(b+="="+c);la.cookie=b}function N(){document.addEventListener?
(B(document,"DOMContentLoaded",N),_tmr.onready()):document.attachEvent&&"complete"===document.readyState&&(B(document,"readystatechange",N),_tmr.onready())}function oa(){B(window,"load",oa);_tmr.onready();_tmr.onload()}function O(){B(window,"unload",O);B(window,"beforeunload",O);_tmr.unload()}if("[object Array]"===Object.prototype.toString.call(_tmr)){var m=window,h=navigator,la=document,G=window.localStorage||null,$="tmr",t=ua(),F=!1,U=null,na=864E5,ma="tmr_detect",Ba=function(){function a(a,c){var d=
document.createElement("div");d.setAttribute("class",String.fromCharCode(97,100,118,98,108,111,99,107,32,97,100,118,101,114,116,98,108,111,99,107,32,97,109,109,98,108,111,99,107,32,98,45,98,97,110,110,101,114,32,98,45,109,101,100,105,97,45,98,97,110,110,101,114,32,112,117,98,95,51,48,48,120,50,53,48,32,112,117,98,95,51,48,48,120,50,53,48,109,32,109,101,100,105,117,109,95,114,101,99,116,97,110,103,108,101,95,51,48,48,95,50,53,48,32,112,117,98,95,55,50,56,120,57,48,32,108,101,97,100,101,114,98,111,
97,114,100,95,55,50,56,95,57,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,95,54,48,48,32,119,105,100,101,95,115,107,121,115,99,114,97,112,101,114,95,49,54,48,120,54,48,48,32,116,101,120,116,45,97,100,32,116,101,120,116,65,100,32,116,101,120,116,95,97,100,32,116,101,120,116,95,97,100,115,32,116,101,120,116,45,97,100,115,32,116,101,120,116,45,97,100,45,108,105,110,107,115,32,97,100,95,116,101,120,116,32,97,100,95,116,101,120,116,32,98,97,110,110,101,114,95,116,101,120,
116,32,116,101,120,116,45,98,97,110,110,101,114,32,98,45,114,98));d.setAttribute("style","position: absolute !important; top: -9999px !important; left: -9999px !important; width: 1px !important; height: 1px !important;");this.bait=document.body.appendChild(d);this.bait.offsetParent;this.bait.offsetHeight;this.bait.offsetLeft;this.bait.offsetTop;this.bait.offsetWidth;this.bait.clientHeight;this.bait.clientWidth;this.loopNumber=0;this.fnPositive=a||null;this.fnNegative=c||null;var e=this;setTimeout(function(){e._checkBait.call(e)},
1)}a.prototype._checkBait=function(){if(F)this._stop();else{var a=!1;null!==document.body.getAttribute("abp")||null===this.bait.offsetParent||0==this.bait.offsetHeight||0==this.bait.offsetLeft||0==this.bait.offsetTop||0==this.bait.offsetWidth||0==this.bait.clientHeight||0==this.bait.clientWidth?a=!0:void 0!==window.getComputedStyle&&(a=window.getComputedStyle(this.bait,null),a="none"==a.getPropertyValue("display")||"hidden"==a.getPropertyValue("visibility"));(!0===a||10<=++this.loopNumber)&&this._stop();
if(a&&this.fnPositive)try{this.fnPositive()}catch(c){}else if(!a&&10>this.loopNumber){var d=this;setTimeout(function(){d._checkBait.call(d)},50*this.loopNumber)}else try{this.fnNegative()}catch(e){}}};a.prototype._stop=function(){try{document.body.removeChild(this.bait)}catch(a){}};return function(b,c){new a(b,c)}}(),fa=60,P=[],X=0,Q=0,ea=Z(16),y=null,R=0,K="reqNum",q=t&&S(K);null===q?(q=0,t&&C(K,q)):q=parseInt(q,10);var M=t&&S("lvid"),L=t&&S("lvidTS");if(null===M||null===L)M=Z(32),L=""+r(),q=0,t&&
(C("lvid",M),C("lvidTS",L),C(K,q));var s=0,u=[],x=[],Y=[],v="string"===typeof location.hostname&&(-1!=location.hostname.search(/^odnoklassniki\.ru$/)||-1!=location.hostname.search(/\.odnoklassniki\.ru$/)||-1!=location.hostname.search(/^ok\.ru$/)||-1!=location.hostname.search(/\.ok\.ru$/)),E="string"===typeof location.hostname&&(-1!=location.hostname.search(/^vk\.com$/)||-1!=location.hostname.search(/\.vk\.com$/)),z="string"===typeof location.hostname&&(-1!=location.hostname.search(/^lamoda\.ru$/)||
-1!=location.hostname.search(/\.lamoda\.ru$/)),Ca="string"===typeof location.search&&-1!=location.search.search(/[?&]rb_clickid=/),l="string"===typeof location.search&&-1!=location.search.search(/[?&]tmr_debug=1(?:&|$)/),pa=v||E||z,Da=!Ca,Ea=v||E,Fa=v||E,qa=v||E,ka=!1,xa="ontouchstart"in m||1<(h.maxTouchPoints||h.msMaxTouchPoints)?"1":"0",ya=window.devicePixelRatio||0,V="";if(h.plugins&&h.plugins["Shockwave Flash"])V=h.plugins["Shockwave Flash"].description.split(" ")[2];else if(window.ActiveXObject)try{var A=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),A=A.GetVariable("$version"),A=A.split(" ")[1].split(","),V=A[0]+"."+A[1]}catch(Ga){}var m=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},D=m.timing||{},W=m.navigation||{},ga="unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" "),
T=!D?void 0:D.navigationStart;f.prototype.pageView=function(a){H(a);var b;if(b=a&&"object"===typeof a)if(b="id"in a)if(b=5>x.length){b:{for(b=0;b<x.length;b++)if(x[b]===a.id){b=!0;break b}b=!1}b=!b}b&&(x.push(a.id),!1!==a.beat&&Y.push(a.id),u.push(a),F&&aa(a));if(b=I("pageView",a,{title:"Page view",id:!0,optional:{url:location.href}}))"start"in a&&P.push(a),g(k(a,!1,!1,!0)),Q=r(),l&&J(b)};f.prototype.reachGoal=function(a){H(a);var b=I("reachGoal",a,{title:"Reach goal",id:s,value:!0,required:{goal:!0},
optional:null,fn:null});if(b&&"goal"in a&&a.goal){var c="";"value"in a&&a.value&&(c=parseInt(a.value)||"");g(k(a,!0,!1,!0)+(";e="+escape("RG:"+c+"/"+a.goal)));l&&J(b)}};f.prototype.itemView=function(a){var b=I("itemView",a,{title:"Item view",id:s,optional:{list:!0,productid:!0,pagetype:!0,totalvalue:!0},fn:function(a,b){return(""+b).replace(/;/g," ")}});if(b){var c=a.list||"",d=a.productid||"",e=a.pagetype||"",f=a.totalvalue||0;(new Image).src=ba(0)+"//ad.mail.ru/retarget/?counter="+b.id+"&list="+
c+"&productid="+d+"&pagetype="+e+"&totalvalue="+f+"&_="+Math.random();c="IV:"+f+"/"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ")+";"+(""+e).replace(/;/g," ");g(k(a,!0,!1,!1)+(";e="+escape(c)));l&&J(b)}};f.prototype.sendEvent=function(a){H(a);var b=I("sendEvent",a,{title:"Send event",id:s,value:!0,required:{category:!0,action:!0},optional:{label:!0},fn:function(a,b){return(""+b).substr(0,300).replace(/;/g," ")}});if(b&&"category"in a&&a.category&&"action"in a&&a.action){var c=(""+a.category).substr(0,
300),d=(""+a.action).substr(0,300),e="";"label"in a&&a.label&&(e=(""+a.label).substr(0,300));var f="";"value"in a&&a.value&&(f=parseInt(a.value)||"");c="CE:"+f+"/"+(""+c).replace(/;/g," ")+";"+(""+d).replace(/;/g," ")+";"+(""+e).replace(/;/g," ");g(k(a,!0,!1,!1)+(";e="+escape(c)));l&&J(b)}};f.prototype.setUserID=function(a){if(null===a||!1===a||void 0===a)this.deleteUserID();else{var b=typeof a;"number"!==b&&"string"!==b?l&&console.warn("[TopMailRu]: Invalid user ID in setUserID"):(y=a,l&&console.info("[TopMailRu]: Global user ID = "+
y))}};f.prototype.deleteUserID=function(){y=null;l&&console.info("[TopMailRu]: Reset global user ID to null")};f.prototype.processEvent=function(a){if(a&&"object"===typeof a)if("type"in a)switch(a.type){case "pageView":this.pageView(a);break;case "reachGoal":this.reachGoal(a);break;case "itemView":this.itemView(a);break;case "sendEvent":this.sendEvent(a);break;case "setUserID":"userid"in a&&this.setUserID(a.userid);break;case "deleteUserID":this.deleteUserID()}else l&&console.warn("[TopMailRu]: Unspecified push event type");
else l&&console.warn("[TopMailRu]: Invalid push event")};f.prototype.push=function(a){for(var b=0,c=arguments.length;b<c;b++)this.processEvent(arguments[b])};var ra=!1;f.prototype.onready=function(){ra||(ra=!0,!ka&&!F&&Ba(za,Aa))};var sa=!1;f.prototype.onload=function(){if(!sa){sa=!0;if(!Fa&&0<P.length){R=r();for(var a=0,b;b=P[a];a++)g(k(b,!0,!0,!1)+";e="+escape("RT/load")+";et="+R);Q=R;P=[]}Da||setTimeout(function(){ia(2)},2E3);Ea||setTimeout(function(){ia(15)},15E3)}};f.prototype.beat=function(){if(!pa&&
0!=Y.length&&X){var a=r(),b=a-X;if(!(12E4<b)){if(12E4<a-Q)for(var c=0;c<u.length;c++)!1!==u[c].beat&&g(k(u[c],!0,!1,!0)+";e="+escape("RT/resend")+";et="+R+";active="+(b?"1":"0"));else g(ha(Y,"RT/beat"));Q=a}}};var ta=!1;f.prototype.unload=function(){ta||(ta=!0,!qa&&0<x.length&&g(ha(x,"RT/unload")))};f.prototype.activity=function(a){X=r()};m=new f;h=0;for(v=_tmr.length;h<v;h++)(z=_tmr[h])&&"object"===typeof z&&H(z);h=0;for(v=_tmr.length;h<v;h++)z=_tmr[h],m.processEvent(z);_tmr=m;if("complete"===document.readyState||
"loading"!==document.readyState&&!document.documentElement.doScroll)_tmr.onready();else document.addEventListener?w(document,"DOMContentLoaded",N):document.attachEvent&&w(document,"readystatechange",N);if("complete"===document.readyState)_tmr.onload();else w(window,"load",oa);qa||(w(window,"unload",O),w(window,"beforeunload",O));if(!pa&&0<x.length){setInterval(_tmr.beat,3E4);try{m=function(a){function b(a){w(document,a,function(){_tmr.activity(a)})}for(var c=0;c<a.length;c++)b(a[c])},m(["scroll",
"gesturechange","touchmove"]),m(["mousedown","mousemove","mouseup","touch"]),w(window,"scroll",function(){_tmr.activity("scallback")})}catch(Ha){}}}})();
