(function(){var d=void 0,g=true,i=null,j=false;function k(){return function(){}}function l(a){return function(){return this[a]}}function m(a){return function(){return a}}var n,q=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b,c){return a.call.apply(a.bind,arguments)}function ca(a,b,c){if(!a)throw Error();if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function s(a,b,c){s=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ba:ca;return s.apply(i,arguments)}function ea(a,b){function c(){}c.prototype=b.prototype;a.ka=b.prototype;a.prototype=new c;a.prototype.constructor=a};function fa(){}
function ga(a,b,c){switch(typeof b){case "string":ia(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==i){c.push("null");break}if(aa(b)=="array"){var e=b.length;c.push("[");for(var f="",h=0;h<e;h++)c.push(f),ga(a,b[h],c),f=",";c.push("]");break}c.push("{");e="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(h=b[f],typeof h!="function"&&(c.push(e),ia(f,c),c.push(":"),ga(a,h,c),e=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var ja={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},ka=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function ia(a,b){b.push('"',a.replace(ka,function(a){if(a in ja)return ja[a];var b=a.charCodeAt(0),f="\\u";b<16?f+="000":b<256?f+="00":b<4096&&(f+="0");return ja[a]=f+b.toString(16)}),'"')};var na={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},oa={scroll:2E4,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function pa(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function qa(a,b){var c="",e=ra(encodeURIComponent(a));e.splice(b||5,e.length);t(e,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",e;a>0;)e=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(e)+b,a>>>=6;a=b}c+=a});return c}
function ra(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,e=4023233417,f=2562383102,h=271733878,o=3285377520,r=[],p,D,F,Q,X,ha=Math.ceil((a.length/4+2)/16),da=[ha],N=0,E;N<ha;N++){da[N]=[];for(p=0;p<16;p++)da[N][p]=a.charCodeAt(N*64+p*4)<<24|a.charCodeAt(N*64+p*4+1)<<16|a.charCodeAt(N*64+p*4+2)<<8|a.charCodeAt(N*64+p*4+3)}N=(a.length-1)*8;a=ha-1;da[a][14]=Math.floor(N/Math.pow(2,32));da[a][15]=N&4294967295;for(N=0;N<ha;N++){for(E=0;E<16;E++)r[E]=
da[N][E];for(E=16;E<80;E++)r[E]=(r[E-3]^r[E-8]^r[E-14]^r[E-16])<<1|(r[E-3]^r[E-8]^r[E-14]^r[E-16])>>>31;a=c;p=e;D=f;F=h;Q=o;for(E=0;E<80;E++)X=Math.floor(E/20),X=(a<<5|a>>>27)+(X==0?p&D^~p&F:X==1?p^D^F:X==2?p&D^p&F^D&F:p^D^F)+Q+b[X]+r[E]&4294967295,Q=F,F=D,D=p<<30|p>>>2,p=a,a=X;c=c+a&4294967295;e=e+p&4294967295;f=f+D&4294967295;h=h+F&4294967295;o=o+Q&4294967295}return[c,e,f,h,o]}
function sa(a){var b=q.navigator,c=q.window.screen,e=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];t(b.plugins,function(a){e.push(a.name+a.description+a.filename+a[0].type)});b=q.performance;e=e.concat([b&&b.now?b.now():"",document.title,q.location.href,u(),pa()]);return e.concat(a||[]).join()}function v(a,b,c){var e=Array.prototype.slice,f=e.call(arguments,2);return function(){return a.apply(b,f.concat(e.call(arguments)))}}
function w(a){return typeof a!=="undefined"}function ta(a){return a.replace(/^www\./,"")}var ua=/^((https?\:)?(\/\/))/i;function va(a){return a.replace(ua,"")}var wa=/^((https?\:)?(\/\/))?[^\/]*/;function xa(a){return a.replace(wa,"")}var ya=/\#.*/;function za(a){return a.replace(ya,"")}var Aa=/\?[^\#]*/;function Ba(a){return a.toLowerCase()}var Ca=/\/+((\?|\#).*)?$/;function Da(a){return a.replace(Ca,"$1")}function Ea(a){return a.replace(Aa,"")}
function Fa(a,b){if(a===b)return 0;var c=i;t([Ba,Da,va,xa,za,Ea],function(e,f){a=e(a);b=e(b);if(a===b)return c=f+1,j});return c}function Ga(a,b,c,e){a.addEventListener?a.addEventListener(b,c,!!e):a.attachEvent&&a.attachEvent("on"+b,c)}function Ha(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function Ia(a){return typeof a==="number"}function x(a){return typeof a==="string"}function Ja(a){return typeof a==="function"}
function Ka(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function u(){return(new Date).getTime()}function La(a){return encodeURIComponent(a)}function Ma(){return q.location.protocol==="https:"?"https:":"http:"}function Na(a){return!!a&&a.constructor===Object}function t(a,b){if(Na(a)===g)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var e=a.length;c<e;c++)if(b(a[c],c)===j)break}}
function Oa(a,b){for(var c=0,e=a.length;c<e;c++)if(b(a[c]))return c;return-1}function Pa(a){var b=q.pSUPERFLY_video,a=Oa(b,a);if(a>-1)return b[a]}function Qa(a){return a===d?0:u()-a}
function Ra(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],e=0,f=b.length;e<=f;e++)c[e]=[e];for(var h=0,o=a.length;h<=o;h++)c[0][h]=h;for(var r,p,D,e=1;e<=f;e++)for(h=1;h<=o;h++)r=e-1,p=h-1,D=c[r][p],b.charAt(r)==a.charAt(p)?c[e][h]=D:(p=c[e][p]+1,r=c[r][h]+1,D+=2,c[e][h]=Math.min(p,r,D));return c[b.length][a.length]}function Sa(a){return a===d?0:u()-a}function y(a){return Math.round(a===-1||isNaN(a)?-1:a*1E3)}
var Ta,Ua=q.setInterval,Va=q.clearInterval,Wa=q.setTimeout,Xa=q.clearTimeout;function Ya(a,b){return Ua(a,b)}function Za(a){switch(a){case d:return"undefined";case "":return"empty";default:return a}}function $a(a){switch(a){case "undefined":break;case "empty":return"";default:return a}};function ab(a,b){var c,b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");var e=[];c=c.getElementsByTagName(b);for(var f=c.length;f--;)c[f].getAttribute(a)&&e.push(c[f]);return e}function bb(a,b,c){c=c||"";if(a===d)a=j;else{var e;if(!(e=c===""&&a.getAttribute(b)))if(e=a.getAttribute(b))e=a.getAttribute(b)===c;a=e?a:a===document.body?j:bb(a.parentNode,b,c)}return a}
function cb(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=ab("data-cb-scroll-element"))&&a.length)return a[0][c];if(Ia(q[b]))return q[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function db(){var a=document,a=a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0;window.innerHeight&&(a=Math.min(window.innerHeight,a));return a}
function eb(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function fb(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return i;var e=a.ownerDocument.documentElement,f=0,h=w(c)?c+1:-1;x(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==e&&f!==h;){if(c(a))return a;a=a.parentNode;f++}return i}
function gb(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}function hb(a){a=a||window.event;return!a?i:fb(a.target||a.srcElement,gb,10)}function ib(a,b){var c=document.createElement(a);t(b,function(a,b){c.setAttribute(b,a)});return c};function jb(){this.ma={};this.Ya=1}function z(a,b,c,e){a.Ya++;a.ma[b]=a.ma[b]||{};a.ma[b][a.Ya]=[c,e];return a.Ya}function kb(a,b){if(x(b))a.ma[b]=d,delete a.ma[b];else if(Ia(b)){var c=g;t(a.ma,function(a){t(a,function(f,h){if(parseInt(h,10)===b)return a[h]=d,delete a[h],c=j});return c})}}jb.prototype.xa=function(a,b){if(this.ma[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];t(this.ma[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
jb.prototype.addEventListener=function(a,b){var c=z(this,a,b);b._cbEventId=c};jb.prototype.removeEventListener=function(a,b){this.ma[a]&&this.ma[a][b._cbEventId]&&this.ma[a][b._cbEventId][0]===b&&kb(this,b._cbEventId)};var A=new jb;var B={};
B.H=function(){B.Rb?B.tb("pageload"):(B.Uc=[{target:q,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:q,event:"resize"},{target:document.body,event:"mousedown"}],B.zb=i,B.Ja=i,B.Qb={},B.Pb={},B.Bc={},B.Cb={},t(B.Uc,function(a){var b=a.event;Ga(a.target,b,function(a){B.tb.call(B,b,a)})}),z(A,"f",function(){B.tb("focus")}),B.tb("pageload"),Ga(document.body,"click",function(a){(a=hb(a))&&A.xa("c",a)},g),Ga(document.body,"contextmenu",function(a){(a=hb(a))&&
A.xa("r",a)}),B.Rb=g)};B.ad=function(){var a,b=B.Bc.keydown;if(b===d)return j;b=u()-b;return b<=(a||15E3)&&b>=0};B.$a=function(a,b){var c=B.Cb[a];if(!c)return"";var b=b||u(),e,f=0;t(c,function(a){e=Math.floor((b-a)/1E3);e>=0&&e<16&&(f|=1<<e)});c=("0000"+f.toString(16)).slice(-4);return c=="0000"?"":c};B.be=function(){B.Cb={}};B.qc=100;
B.tb=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}B.ie(a);if(B.zb===i)B.Pc(a);else if(!B.Ja||na[B.Ja]<na[a]||oa[B.Ja]<oa[a])B.Ja=a};B.ie=function(a){var b=u();B.Bc[a]=b;var c=B.Cb[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();B.Cb[a]=c};
B.Pc=function(a){B.zb=Wa(B.gd,B.qc);A.xa("a");B.Qb[a]!==i&&Xa(B.Qb[a]);B.Pb[a]!==i&&Xa(B.Pb[a]);B.Nc(a,B.Qb,na,"i");B.Nc(a,B.Pb,oa,"j")};B.Nc=function(a,b,c,e){b[a]=Wa(function(){Xa(b[a]);delete b[a];var c=j;t(b,function(){c=g;return j});c||A.xa(e)},c[a]+B.qc)};B.gd=function(){Xa(B.zb);B.zb=i;if(B.Ja)B.Pc(B.Ja),B.Ja=i};var lb,mb,nb,ob,pb;(function(){var a,b;t(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof q.document[a]==="boolean")return b=c,j});b!==d&&(ob=a,pb=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),nb=b+"visibilitychange")})();var qb=j;function rb(){qb=pb&&q.document[pb]==="prerender"?g:j}function sb(){mb=g;A.xa("f")}function tb(){mb=j;A.xa("b")}
function ub(a,b,c){q.addEventListener?q.addEventListener(a,c,j):q.document.attachEvent&&q.document.attachEvent(b,c)}function vb(){var a=g;q.document.hasFocus&&(a=q.document.hasFocus());var b=j;ob&&(b=q.document[ob]);return a&&!b}function wb(){vb()?sb():tb()}function xb(a){rb();if(qb){var b=j,c=function(){b||(rb(),qb||(b=g,a(),q.window.setTimeout(function(){q.document.removeEventListener(nb,c,j)},100)))};q.document.addEventListener(nb,c,j)}else a()};function yb(){this.k=q._sf_async_config||{};this.vc=v(this.Hc,this)}yb.prototype.H=function(){this.Jc=0};yb.prototype.Hc=k();yb.prototype.hb=function(a){if(!qb){var b=this.vc,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};yb.prototype.wa=function(){this.vc=i};function zb(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace(/\+/g," "),t(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function Ab(a,b){var c="",e=q.location.href.match(/[^?]+[?]([^#]+).*/);if(e){var e=zb(e[1]),f=b||a;e[f]&&(c=e[f])}return encodeURIComponent(c)}function Bb(a,b){return!b?g:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function Cb(a){var b=[];t(Db,function(c){var e=a[c];w(e)&&(Object.prototype.toString.call(e)==="[object Array]"?t(e,function(a){b.push(c+"="+a)}):Na(e)?t(e,function(a,c){b.push(c+"="+a)}):((e+"").length||c=="r")&&b.push(c+"="+e))});b.push("_");return b.join("&")}
function Eb(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),e=q.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0&&a.indexOf("app:")<0)if(a.indexOf("//")===0)a=e.protocol+a;else if(a.indexOf("/")===0)var f=Bb(e.protocol,e.port)?"":e.port,a=e.protocol+"//"+e.hostname+(f?":"+f:"")+a;else{var f=document.baseURI||e.href,h=f.indexOf("?");h===-1&&(h=f.indexOf("#"));if(h===-1)h=f.length;h=f.lastIndexOf("/",h);a=h===-1?
"/"+a:f.substr(0,h)+"/"+a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=e.hostname;if(b.protocol==="")b.protocol=e.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(Bb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function Fb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function C(a,b,c){a[b]=a[b]||c}function Gb(a,b){for(var c=q[a]||[];c.length;)b(c.shift());q[a]={push:b}}function Hb(a){t(document.getElementsByTagName("script"),function(b){if(typeof b.src==="string"&&b.src.match(/chartbeat.js/))return b=zb(b.src.split("?")[1]),C(a,"uid",b.uid),C(a,"domain",b.domain),j})}function Ib(a,b){return a[b]?encodeURIComponent(a[b]):""}function Jb(a){var b={};t(a,function(a,e){e.charAt(0)=="_"&&(b[e]=a)});return b};var G={};G.dd=function(a){try{G.create("_cb_test","1",1,a);var b=G.F("_cb_test");G.remove("_cb_test",a);return b==="1"}catch(c){return j}};G.F=function(a){a+="=";var b="";t(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
G.create=function(a,b,c,e){var f=q._sf_async_config;if(f&&f.noCookies)return"";f=new Date;f.setTime(u()+c*1E3);a=a+"="+b+("; expires="+f.toGMTString())+("; path="+e);return document.cookie=a};G.remove=function(a,b){return G.F(a)?G.create(a,"",-86400,b):""};var H={};H.Y=function(a){var b=q._sf_async_config;if(!a&&b&&b.noCookies)return i;if(H.Y.Ib!==d)return H.Y.Ib;var a=u()+"",c,e;try{if((e=q.localStorage).setItem(a,a),c=e.getItem(a)===a,e.removeItem(a),c)return H.Y.Ib=e}catch(f){}return H.Y.Ib=i};H.F=function(a){var b=H.Y();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&u()>c)?(H.remove(a),""):b.getItem(a)||""};
H.create=function(a,b,c){var e=H.Y();if(e){var f=new Date;f.setTime(u()+c*1E3);try{e.setItem(a,b),e.setItem(a+"_expires",f.getTime())}catch(h){}}};H.remove=function(a){var b=H.Y();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Kb(a,b){this.vb=a||"";this.Ba=b||"/";this.hd=H.Y()!==i||G.dd(this.Ba);this.ic=j;Lb(this)}n=Kb.prototype;n.isSupported=l("hd");
function Lb(a){if(!G.F("_cb_ls")){var b=H.Y()!==i,c=G.F("_SUPERFLY_lockout");c&&t(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,g)});var e=G.F("_chartbeat3");e&&(a.create("_v__chartbeat3",e,34128E3,g),G.remove("_chartbeat3",a.Ba));b&&((b=G.F("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,g),(b=G.F("_chartbeat5"))&&a.create("_chartbeat5",b,60,g));G.create("_cb_ls","1",34128E3,a.Ba)}}function Mb(a){var b=a.ic;a.ic=j;return b}
n.create=function(a,b,c,e){a=e?a:this.vb+a;(H.Y()?H:G).create(a,b,c,this.Ba);H.Y()&&G.create(a,b,c,this.Ba)};n.update=function(a,b,c,e,f,h,o){a=e?a:this.vb+a;f=x(f)?f:"::";e=(e=this.F(a,g))?e.split(f):[];if(o&&e.length){var r=o(b),p=Oa(e,function(a){return o(a)===r});p!==-1&&e.splice(p,1)}e.push(b);for(Ia(h)&&e.length>h&&e.splice(0,e.length-h);e.length>1&&e.join(f).length>4E3;)e.shift();this.create(a,e.join(f),c,g)};
n.F=function(a,b){var a=b?a:this.vb+a,c=(H.Y()?H:G).F(a);if(!c&&H.Y()&&(c=G.F(a))&&G.F("_cb_ls")){this.ic=g;var e;switch(a){case "_SUPERFLY_lockout":e=600;break;case "_chartbeat4":e=60;break;case "_cb_cp":e=60;break;case "_chartbeat3":e=34128E3;break;default:e=34128E3}H.create(a,c,e)}return c};n.remove=function(a,b){a=b?a:this.vb+a;(H.Y()?H:G).remove(a,this.Ba);H.Y()&&G.remove(a,this.Ba)};function Nb(a){var b=i;if(a&&(b=Ob(),b=!b?b:I(b.pathname)+b.search+b.hash))return b;var c=q.location,b=I(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),e=/&utm_[^=]+=[^&]+/ig;(c=e.exec(c.search))&&(a=a.replace(e,""));e=/\?utm_[^=]+=[^&]+(.*)/i;(c=e.exec(a))&&(a=a.replace(e,c[1]!=""?"?"+c[1]:""));return b+a}function Pb(a){return a&&(a=Ob(),a=!a?a:a.hostname)?a:q.location.hostname}function Ob(){var a=Qb();return!a?a:Eb(a.href)}
function Qb(){var a=i;t(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return a=b,j});return a}for(var Rb={},Sb=0;Sb<81;Sb++)Rb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Sb)]=g;function Tb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Rb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}
function I(a){if(!x(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Tb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function J(a,b){var c=K();return w(b)&&!w(c[a])?b:c[a]}function K(){w(q._cb_shared)||(q._cb_shared={});return q._cb_shared};var L={Xc:{IDLE:0,Wc:1,Vc:2,Eb:3},Yc:{IDLE:0,Wc:1,Vc:2,Eb:3},pa:0,qa:0};L.H=function(){if(!L.Rb)z(A,"a",L.qd,L),z(A,"i",L.ud,L),z(A,"f",L.sd,L),z(A,"b",L.rd,L),z(A,"j",L.td,L),L.Rb=g};L.J=function(){return L.pa};L.od=function(){return L.qa};L.qd=function(){L.pa===1?L.Fa(3):L.pa===0&&L.Fa(2);L.qa===1?L.Ea(3):L.qa===0&&L.Ea(2)};L.ud=function(){L.pa===3?L.Fa(1):L.pa===2&&L.Fa(0)};L.td=function(){L.qa===3?L.Ea(1):L.qa===2&&L.Ea(0)};L.sd=function(){(L.pa===0||L.pa===2)&&L.Fa(3);(L.qa===0||L.qa===2)&&L.Ea(3)};
L.rd=function(){L.pa===3?L.Fa(2):L.pa===1&&L.Fa(0);L.qa===3?L.Ea(2):L.qa===1&&L.Ea(0)};L.Fa=function(a){L.pa=a;A.xa("s",a)};L.Ea=function(a){L.qa=a;A.xa("x",a)};function Ub(a,b){this.Ob=a||d;this.Xb=b||d;this.Qa=this.ua=0;this.Ac=v(this.zd,this);this.hc=this.ra=i}n=Ub.prototype;n.H=function(){this.Qa=this.ua=0;this.ra=i;this.hc=z(A,"s",this.bb,this);this.bb(L.J())};n.bb=function(a){Va(this.ra);this.ra=i;if(a===L.Xc.Eb)this.ra=Ua(this.Ac,1E3)};n.zd=function(){if(this.Ob===d||this.Ob())this.ua++,this.Qa++,this.Xb&&this.Xb()};n.terminate=function(){Va(this.ra);this.ra=i;kb(A,this.hc)};n.wa=function(){this.terminate();this.Xb=this.Ob=d};function Vb(a,b){Ub.call(this,a,b)}ea(Vb,Ub);Vb.prototype.H=function(){this.Qa=this.ua=0;this.ra=i;this.hc=z(A,"x",this.bb,this);this.bb(L.od())};Vb.prototype.bb=function(a){Va(this.ra);this.ra=i;if(a===L.Yc.Eb)this.ra=Ua(this.Ac,1E3)};function Wb(){yb.call(this);this.Na=[];this.q=new Kb(this.Rc,this.k.cookiePath||"/");this.q.remove("_SUPERFLY_nosample");this.la=new Ub;this.Ka=new Vb;this.Zb=v(this.fb,this);Ga(q,"unload",this.Zb);xb(v(this.H,this))}ea(Wb,yb);n=Wb.prototype;n.fc=g;
n.H=function(){Wb.ka.H.call(this);this.pb=this.Ra=0;this.Ga=u();this.Da=qa(Xb(this));this.dc=g;this.rb=72E5;if(this.fc){var a=+this.k.sessionLength;if(!isNaN(a))this.rb=a*6E4}a=J("d");if(!a){var a=[],b=this.q.F("_chartbeat2",g);b.length>0&&(a=b.split("."));a.length>5&&(a=[]);var b=u(),c=this.q.F("_cb",g);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var e=b-+(a[1]||0),f=b-+(a[2]||0);K().n=c&&e>18E5&&f<2592E6?0:1;e=a[4];if(!(f=f>18E5))if(Yb(this))f=j;else{var f=Zb(this),f=decodeURIComponent(f),f=$b(f)||f,
h;h=ac(this);h=decodeURIComponent(h);h=$b(h)||h;f=f!==h}if(!e||f)e=qa(Xb(this)),a[4]=e,this.q.remove("_cb_svref",g);f="1";h=a&&+a[2];e=a&&a[3];if(a&&h&&e)if(f=Math.abs((Ka(b)-Ka(h))/864E5)){f=Math.min(f,16)-1;for(h="";f--;)h+=0;f=(e+h+"1").slice(-16)}else f=e;e=f;c||(c=this.k.utoken||qa(Xb(this),3),a[1]=b);a[2]=b;a[3]=e;this.k.utoken=this.ib;this.q.create("_cb",c,34128E3,g);this.q.create("_chartbeat2",a.join("."),34128E3,g);a[0]=c;K().d=a}this.re=a.join(".");var o;c=+a[1];e=+a[2];if((b=a[3])&&c&&
e)o=(Math.min((Math.abs((Ka(e)-Ka(c))/864E5)||0)+1,16,b.length)-1).toString(16),o+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.zc=o;this.Ub=J("n",1);this.ib=a[0];this.ee=a[4];this.de=ac(this);this.q.create("_cb_svref",ac(this)||"null",1800,g);this.la.H();this.Ka.H();L.H();B.H();lb||(mb=vb(),nb&&q.document.addEventListener&&q.document.addEventListener(nb,wb,j),ub("focus","onfocusin",sb),ub("blur","onfocusout",tb),mb&&sb(),lb=g);this.eb=0;this.$c=z(A,"a",this.Cd,this)};
function bc(a){if(!a.q.F("_SUPERFLY_lockout")&&!qb)a.Bd?a.xb():(a.Bd=g,!q._sf_async_config&&!q._cbq?(a.ub=v(a.xb,a),Ga(q,"load",a.ub)):a.xb())}n.xb=function(){this.gb=cc();B.H();this.ob=Ya(v(this.na,this),15E3);this.na()};
n.na=function(){var a=this.la.Qa,a=this.k.reading&&+this.k.reading||a>0;if(this.pb<this.Ra&&!a)this.pb++;else{var b;if(Ta===d)b=q.navigator.userAgent,Ta=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Ta;b&&!a?this.pb++:(a?this.Ra=0:this.Hb(),this.pb=0,this.Na.push(0),this.Na.length>18&&this.Na.shift(),this.fc&&u()-this.Ga>=this.rb?this.terminate():this.Va())}};
n.Hc=function(){this.Na.push(1);var a=0;t(this.Na,function(b){a+=b});a<3?(this.dc=g,this.Hb()):(this.terminate(),this.q.create("_SUPERFLY_lockout","1",600))};n.fb=k();n.Cd=function(){var a=dc(this);this.eb=Math.max(this.eb,a)};function dc(a){return Math.floor(cb(!!a.k.scrollElement))}n.Hb=function(){var a=this.Ra;this.Ra=a=a?Math.min(a*2,16):1};n.nb=function(){this.fb();this.terminate()};n.Qc=function(){this.H();bc(this)};
function Yb(a){if(a.k.virtualReferrer)return g;if(ec(a))return j;a=document.referrer.indexOf("://"+q.location.hostname+"/");return a!=-1&&a<9}function ec(a){var b=a.k.referrerOverrideQueryParam,c="";t(window.location.search.substr(1).split("&"),function(a){a=a.split("=");if(a.length==2&&a[0]==b&&a[1])return c=decodeURIComponent(a[1]).replace(/\+/g," "),j});c&&c.indexOf("::")==-1&&(c="external::"+c);return c}
function Zb(a){a=a.k.virtualReferrer||ec(a);if(!a&&(a=document.referrer||"")&&!/^(android-)?app:/.test(a)){var b=Eb(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=I(b.pathname),a=Fb(b)}return encodeURIComponent(a)}function fc(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function Xb(a){a=[Zb(a),eb("Width"),eb("Height")];return sa(a)}
function gc(a){var b=[],c=a.q.F("_chartbeat4");c&&(t(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.q.remove("_chartbeat4"));return b}function ac(a){a=a.q.F("_cb_svref",g)||Zb(a)||"null";a==="null"&&(a="");return a}function $b(a){a=a.match(/^https?:\/\/([^\/]*)/);return!a?i:a[1]}function cc(){var a=q.performance&&q.performance.timing;if(!a||a.navigationStart==0)return-1;var b=a.navigationStart,a=a.loadEventStart;return Ia(b)&&b?Ia(a)&&a>b?a-b:u()-b:-1}
n.terminate=function(){this.la.terminate();this.Ka.terminate();kb(A,this.$c);this.ub!==d&&Ha(q,"load",this.ub);Va(this.ob);K().d=d;K().n=d};n.wa=function(){this.terminate();Ha(q,"unload",this.Zb);this.Zb=this.ub=this.q=this.Na=this.k=i;this.la.wa();this.la=i;this.Ka.wa();this.Ka=i;Wb.ka.wa.call(this)};function hc(a){for(var b=J("m")||[];b.length;)a(b.shift());a={push:a};K().m=a};function ic(a){var b=a.offsetLeft,c=a.offsetTop,e=jc(a);b+=e.x;c+=e.y;for(var f=j,e=a.offsetParent;a&&a!==d&&a!==document.body;){if(a===e)e=jc(a),b+=a.offsetLeft+e.x,c+=a.offsetTop+e.y,e=a.offsetParent;if(kc(a,["position"]).position==="fixed"){f=g;break}a=a.parentElement}f&&(b+=0,c+=0);return{x:b,y:c}}
function kc(a,b){var c={},e,f;q.getComputedStyle?e=q.getComputedStyle(a,i):a.currentStyle?f="currentStyle":a.style&&(f="style");t(b,function(b){c[b]=e?e[b]||e.getPropertyValue(b):a[f][b]});return c}var lc=/matrix(3d)?\((.*)\)/;function jc(a){var b={x:0,y:0},a=kc(a,["transform"]).transform;if(!x(a))return b;var c=a.match(lc);if(!c)return b;var a=c[2].split(", "),e;w(c[1])?(c=12,e=13):(c=4,e=5);b.x=parseInt(a[c],10);b.y=parseInt(a[e],10);return b};function mc(){var a=q.location.href,a=a.replace(/-{2,}/g,"-"),a=Eb(a);a.pathname=I(a.pathname);return a}
function nc(a){var b=G.F("_chartbeat6");if(!b)return i;var b=b.split("::"),c,e;if(b.length===1)c=b[0].split(","),e=0;else{var f,h=mc(),o=Fb(h);t(b,function(a,b){var h=a.split(","),p=Ra(o,decodeURIComponent(h[0]));if(p===0)return c=h,e=b,j;if(f===d||p<f)f=p,c=h,e=b})}b.splice(e,1);a="_chartbeat6="+b.join("::")+oc(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),h=decodeURIComponent(c[1]),r=c[2];c.splice(0,3);for(var p=c.length/3,D=0;D<p;D++){var F=D*3+2;a.push({oe:b,origin:h,Sa:r,Wa:F<c.length?
c[F]:"",kd:c[D*3],je:c[D*3+1]})}return a}function oc(a){var b="",c;if(!Na(a))return b;a.Ec&&(c=new Date,c.setTime(c.getTime()+a.Ec),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function pc(a){var b=a.topStorageDomain,a=a.domain,c=q.location.hostname;return b?b:qc(c,a)?a:c.replace(/^www\./,"")}
function qc(a,b){if(a===b)return g;for(var c=b.split("."),e=a.split(".");c.length;){if(e.length===0)return j;if(c.pop()!==e.pop())return j}return g}function rc(a,b,c,e,f){this.md=a;this.ld=b;this.ke=c;this.Sa=e;this.Wa=f}function sc(a){var b=a.d,c=i;if(b!==i){var e={};b.s&&t(b.s,function(a,b){e[b]=typeof a==="string"?{sc:a,Wa:""}:{sc:a.chosenVariant,Wa:a.specificLocation}});c={Oc:e,Sa:b.g,Dc:b.m}}return{status:a.s,data:c,code:a.c,message:a.m}};function tc(a,b){for(var c=b||document.documentElement,e=[],f=i,h=a,o,r,p,D,F,Q;h&&h!==c;){o=h.nodeName.toLowerCase();f=h;r=f.nodeName;if((h=h.parentNode)&&h!==document.documentElement){p=h.children;D=0;for(F=0,Q=p.length;F<Q;F++){if(f===p[F]){o+="["+(1+F-D)+"]";break}p[F].nodeName!==r&&D++}}e.unshift(o)}return e.join("/")};function uc(){this.Rc="_t_";Wb.call(this)}ea(uc,Wb);n=uc.prototype;
n.H=function(){uc.ka.H.call(this);Hb(this.k);var a=!!this.k.useCanonical,b=Pb(!!this.k.useCanonicalDomain&&a);C(this.k,"mabServer","mabping.chartbeat.net");C(this.k,"title",document.title);C(this.k,"domain",b);this.k.path=this.k.path?I(this.k.path):Nb(a);this.ja=ta(b);this.k.domain=ta(this.k.domain);this.he=pc(this.k);this.Za=this.qb=j;this.wc=[];var c=this,a=nc({domain:"."+this.he,Ec:6E4,path:"/"});if(a!==i)this.qb=g,t(a,function(a){c.wc.push(new rc(a.origin,a.kd,a.je,a.Sa,a.Wa))});this.Fc=0;this.yb=
i;hc(v(this.yd,this))};n.Va=function(){var a=this.la.ua,b=vc(this),c,e=this;this.qb&&t(this.wc,function(f){c=b+"&x="+f.ld+"&v="+f.ke+"&ml="+f.Sa+"&xo="+f.md+"&e="+a+"&sl="+f.Wa;e.hb(c)});!this.Za&&this.yb&&wc(this,this.yb);this.Za=g};n.xb=function(){this.gb=cc();B.H();if(this.qb)this.ob=Ya(v(this.na,this),500);this.na()};n.na=function(){var a,b;this.Za?(a=this.la.ua,b=this.Fc*15,a-b>=15&&(this.Va(),this.Fc+=1),a>=45&&this.terminate()):this.Va()};
function vc(a){var b=a.k;return Ma()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.ja)+"&u="+a.ib+"&c="+Math.round((u()-a.Ga)/600)/100}n.fb=k();n.fe=function(a){a=sc(a);this.Za?wc(this,a):this.yb=a};
function wc(a,b){var c=vc(a),e=b.status,f=b.data;if(e=="s"&&f!==i){var h=v(a.hb,a);Na(f.Oc)&&t(f.Oc,function(a,b){h(c+"&x="+b+"&v="+a.sc+"&ml="+f.Sa+"&sl="+a.Wa+"&e=-1")});Object.prototype.toString.call(f.Dc)==="[object Array]"&&t(f.Dc,function(a){h(c+"&me=3&ml="+f.Sa+"&x="+a)})}else e=="e"&&a.hb(c+"&me="+b.code)}n.yd=function(a,b){for(var c=0,e=arguments.length;c<e;c++){var a=arguments[c],f=a.shift();f==="t"?this.fe.apply(this,a):f==="v"&&this.ce.apply(this,a)}};
n.nb=function(){K().m=[];w(this.lc)&&this.lc();uc.ka.nb.call(this)};n.ce=function(a){this.lc=a};n.terminate=function(){this.lc=this.pe=d;this.yb=i;this.Za=this.qb=d;uc.ka.terminate.call(this)};if(!q.pSUPERFLY_mab){var xc=new uc,yc={};yc.evps=v(xc.nb,xc);yc.svps=v(xc.Qc,xc);q.pSUPERFLY_mab=yc;bc(xc)};var zc,Ac,Bc;
function Cc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);Dc();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=w(d)?d:{},b.src=a,a=ib("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],w(d)?d.appendChild(a):b&&b.appendChild(a)}}
function Dc(){Xa(Ac);Ac=d;Ha(q,"message",Cc);Bc&&Bc.parentNode&&Bc.parentNode.removeChild(Bc);Bc=d};function Ec(){var a=q._sf_async_config&&q._sf_async_config.domain;if(a&&!zc){zc=g;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);Ga(q,"message",Cc);Ac=Wa(Dc,1E4);var b=w(d)?d:{};b.src=a;a=ib("iframe",b);a.style.display="none";w(d)?d.appendChild(a):document.body&&document.body.appendChild(a);Bc=a}}
function Fc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=H.Y(g),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Ec(),Ha(q,"message",Fc))}};function Gc(){"postMessage"in window&&Ga(q,"message",v(this.vd,this));Wb.call(this);Gb("_cbq",v(this.Mc,this))}ea(Gc,Wb);
Gc.prototype.H=function(){Gc.ka.H.call(this);var a=this.ib;K().u=a;a=this.Da;K().t=a;this.Gb=i;Hb(this.k);var a=!!this.k.useCanonical,b=Pb(!!this.k.useCanonicalDomain&&a);C(this.k,"pingServer","ping.chartbeat.net");C(this.k,"title",document.title);C(this.k,"domain",b);this.k.path=this.k.path?I(this.k.path):Nb(a);this.ja=ta(b);this.k.domain=ta(this.k.domain);this.bd=z(A,"c",this.Gd,this);this.cd=z(A,"r",this.Hd,this);this.Pa=i};Gc.prototype.Zc=function(a){this.Gb=a};
Gc.prototype.fb=function(){this.q.update("_chartbeat4",["t="+this.Da,"E="+this.la.ua,"EE="+this.Ka.ua,"x="+dc(this),"c="+Math.round((u()-this.Ga)/600)/100,"y="+eb("Height"),"w="+db()].join("&"),60,d,d,1)};var Db="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_x,_y,_z,_s,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR,EE,sv,sr".split(",");n=Gc.prototype;
n.Va=function(a){this.Jc++;var b={};b.g=this.k.uid;b.g0=Ib(this.k,"sections");b.g1=Ib(this.k,"authors");b.g2=Ib(this.k,"zone");b.g3=Ib(this.k,"sponsorName");b.g4=Ib(this.k,"type");!this.k.noCookies&&this.q.isSupported()?b.n=this.Ub:b.nc=1;b.c=Math.round((u()-this.Ga)/600)/100;b.E=this.la.ua;b.EE=this.Ka.ua;var c=dc(this);this.eb=Math.max(this.eb,c);b.x=c;b.m=this.eb;b.y=eb("Height");b.o=eb("Width");b.w=db();b.b=this.gb>0?this.gb:"";if(this.zc)b.f=this.zc;b[""]=Jb(this.k);b.t=this.Da;b.V=100;b.tz=
(new Date).getTimezoneOffset();b.sn=this.Jc;b.sv=this.ee;b.sr=this.de;c=this.la.Qa;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.ib;b.d=encodeURIComponent(this.ja);b.j=Math.round((this.Ra+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var e=b.c*6E4+this.Ga;b.eD=B.$a("mousedown",e);b.eM=B.$a("mousemove",e);b.eK=B.$a("keydown",e);b.eR=B.$a("resize",e);b.eS=B.$a("scroll",e);B.be();B.ad()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=Yb(this);if(this.dc){this.dc=
j;if(c)this.Pa=Hc(this);b.i=fc(this);e=this.k.hudTrackable;e!==d&&(b.L=e?"1":"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.Pa){if(b.v=encodeURIComponent(this.Pa.path),b.K=Ic(this.Pa),this.Pa.Vb>1)b.l1=this.Pa.Vb}else b.v=Zb(this);this.k.virtualReferrer&&(b.vp=1)}else b.r=Zb(this);c=Za(b.v);K().v=c;c=Za(b.r);K().r=c;b.A=this.Gb?this.Gb:"";b._c=Ab("utm_campaign",this.k.campaignTag);b._m=Ab("utm_medium",this.k.mediumTag);b._x=Ab("utm_source",this.k.sourceTag);b._y=Ab("utm_content",
this.k.contentTag);b._z=Ab("utm_term",this.k.termTag);this.k.idSync?(c=[],ga(new fa,this.k.idSync,c),c=encodeURIComponent(c.join(""))):c="";b._s=c;b.z=gc(this);b.C=this.k.mobileApp?1:"";b.KK=a?Ic(a):"";b.l=Mb(this.q)?1:"";this.la.Qa=0;this.hb(Ma()+"//"+this.k.pingServer+"/ping?"+Cb(b))};
n.vd=function(a){var b=this.k,c=b.playerdomain||this.ja;if(va(a.origin)===va(c))if(c=a.data,x(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Mc(a));else if(c=="cbdata?"){var c="&u="+J("u"),e="&t="+J("t"),f="&v="+J("v"),h="&r="+J("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+fc(this)+"&referrer="+Zb(this)+"&internal="+(Yb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ja)+
c+e+f+h+"&utoken="+this.ib;a.source.postMessage(b,"*")}};n.Mc=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.Ra=0};function Jc(a){a=a.replace(/-{2,}/g,"-");a=Eb(a);a.pathname=I(a.pathname);return a}n.Gd=function(a){Kc(this,a,"c")};n.Hd=function(a){Kc(this,a,"r")};
function Kc(a,b,c){if(a.fc&&u()-a.Ga>=a.rb)a.terminate();else{var e=b.href||"",e=Jc(e);if(e.protocol.indexOf("http")===0){var f=e.hostname!==q.location.hostname,e=Fb(e),h=fb(b,function(a){return a.id}),o=tc(b,h),r="";a.k.moduleAttribute&&(r=(r=bb(b,a.k.moduleAttribute))?r.getAttribute(a.k.moduleAttribute):"",r=r.replace(/::/g,"-").substr(0,40));h?(o&&(o="/"+o),o="*[@id='"+h.id+"']"+o,h=tc(b)):h=o;o=qa(o);h=qa(h);b=ic(b);c={left:b.x,top:b.y,path:a.k.path,href:e,pc:o,Fb:h,oc:"",gc:c,Vb:0,pd:a.k.domain,
Tb:r};a.Va(c);f||a.q.update("_chartbeat5",Lc(c),60,j,d,3,function(a){a=a.split(",");return a[2]+","+a[3]})}}}function Ic(a){return[a.left,a.top,a.pc,encodeURIComponent(a.oc),a.gc,encodeURIComponent(a.href),a.Fb,a.Tb].join("::")}function Lc(a){var b=encodeURIComponent(a.oc),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.pc,b,a.gc,a.Fb,encodeURIComponent(a.pd),a.Tb].join(",")}
function Hc(a){var b=a.q.F("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,e,f=i,h,o=Jc(q.location.href),r=Fb(o);t(c,function(a,b){var c=a.split(","),o=Fa(r,decodeURIComponent(c[3]));if(o===0)return e=c,f=b,j;else if(o===i)return g;if(h===d||o<h)h=o,e=c,f=b});if(f===i)return i;c.splice(f,1);a.q.create("_chartbeat5",c.join("::"),60);(a=e[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:e[0],top:e[1],path:decodeURIComponent(e[2]),href:decodeURIComponent(e[3]),pc:e[4]||
"",oc:"",Fb:e.length>7?e[7]:"",gc:e.length>6?e[6]:"c",Vb:b,Tb:e[9]?e[9]:""}}n.terminate=function(){kb(A,this.bd);kb(A,this.cd);Gc.ka.terminate.call(this)};var M="ct",O="s1";function P(a){this.a=a;this.D=this.G=j;this.B=u();this.ha()}n=P.prototype;n.ha=function(){this.a.currentTime()>0&&!this.a.paused&&!this.a.ended&&this.fa();this.a.on("play",v(this.fa,this));this.a.on("dispose",v(this.Jd,this));this.a.ready(v(this.oa,this))};n.oa=function(){this.G=g};n.fa=function(){this.D=g};n.Jd=function(){var a=q._cbv;a&&a.push&&a.push(["removePlayer",this.a])};n.O=function(){return this.G&&this.M()!==""};
n.Mb=function(){var a;this.a.cb_configs&&this.a.cb_configs.domain?a=this.a.cb_configs.domain:!a&&q._sf_async_config&&q._sf_async_config.domain&&(a=q._sf_async_config.domain);return a};n.Nb=function(){var a;this.a.cb_configs&&this.a.cb_configs.uid?a=this.a.cb_configs.uid:!a&&q._sf_async_config&&q._sf_async_config.uid&&(a=q._sf_async_config.uid);return a};n.M=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("name")?a.name:this.a.el().getAttribute("title"))||""};
n.N=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("id")?a.id:this.a.el().attributes["data-video-id"]&&this.a.el().attributes["data-video-id"].value?this.a.el().attributes["data-video-id"].value:this.a.src())||""};n.U=function(){return M};n.P=m("");n.ca=function(){var a=this.a.duration();return y(a)};n.J=function(){return!this.D?O:this.a.ended()?"s4":this.a.paused()?"s3":"s2"};n.X=function(){var a=this.a.currentTime();return y(a)};n.T=m(-1);
n.ba=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("thumbnail")?a.thumbnail:this.a.poster())||""};n.Z=k();n.S=k();n.da=function(){return Sa(this.B)};n.$=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.sections?a=this.a.cb_configs.sections.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.sections&&(a=q._sf_async_config.sections.split(","));if(a.length>0&&a[0]!=="")return a};
n.Q=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.authors?a=this.a.cb_configs.authors.split(","):a.length==0&&q._sf_async_config&&q._sf_async_config.authors&&(a=q._sf_async_config.authors.split(","));if(a.length>0&&a[0]!=="")return a};n.aa=m("BCN");P.prototype.getStrategyName=P.prototype.aa;P.prototype.isReady=P.prototype.O;P.prototype.getHost=P.prototype.Mb;P.prototype.getUid=P.prototype.Nb;P.prototype.getTitle=P.prototype.M;P.prototype.getVideoPath=P.prototype.N;
P.prototype.getContentType=P.prototype.U;P.prototype.getAdPosition=P.prototype.P;P.prototype.getTotalDuration=P.prototype.ca;P.prototype.getState=P.prototype.J;P.prototype.getCurrentPlayTime=P.prototype.X;P.prototype.getBitrate=P.prototype.T;P.prototype.getThumbnailPath=P.prototype.ba;P.prototype.getPlayerType=P.prototype.Z;P.prototype.getAutoplayType=P.prototype.S;P.prototype.getViewStartTime=P.prototype.da;P.prototype.getSections=P.prototype.$;P.prototype.getAuthors=P.prototype.Q;
P.verify=function(a){return a.controlBar!==d};function R(a){this.Ya=this.ja=d;this.G=j;this.Lc=this.tc=-1;this.va=i;this.a=a;this.D=j;this.$b=g;this.B=u();this.ac="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var e=a[c];if((e.indexOf("chartbeat")>=0||e.indexOf("localhost")>=0)&&e.indexOf(".js")>=0){this.ac=e;break}}if(this.ac){a=zb(this.ac);if(this.ja=a.domain)this.ja=this.ja.replace(/^video@/,"");this.Ya=a.uid}a=window.brightcove;this.a=a.api.getExperience();b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);
b.getReady()?this.Ic():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,s(this.Ic,this))}n=R.prototype;
n.Ic=function(){var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.tc=Math.round(a)});b.getCurrentVideo(function(a){c.va=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,s(this.Rd,this));b.addEventListener(a.STOP,s(this.Td,this));b.addEventListener(a.COMPLETE,s(this.Id,this));b.addEventListener(a.BEGIN,s(this.fa,this));this.G=g};n.Rd=function(a){this.Lc=a.position;this.za=this.$b=j};n.Td=function(){this.$b=g};
n.Id=function(){this.za=g};n.fa=function(){this.za=j;if(!this.D)this.D=g};n.O=l("G");n.M=function(){var a="";this.va&&(a=this.va.displayName);return a};n.N=function(){var a="";this.va&&(a="video@"+this.ja+"/"+this.va.id);return a};n.U=function(){return M};n.P=m("");n.ca=l("tc");n.J=function(){return!this.D?O:this.za?"s4":this.$b?"s3":"s2"};n.X=function(){return y(this.Lc)};n.T=m(-1);n.ba=function(){var a="";this.va&&(a=this.va.thumbnailURL);return a};n.Z=k();
n.da=function(){return isNaN(this.B)?0:Qa(this.B)};n.Q=k();n.$=function(){var a;this.va&&(a=this.va.tags);return a};n.S=m("unkn");n.aa=m("BC");n.Mb=l("ja");n.Nb=l("Ya");R.prototype.isReady=R.prototype.O;R.prototype.getTitle=R.prototype.M;R.prototype.getVideoPath=R.prototype.N;R.prototype.getContentType=R.prototype.U;R.prototype.getAdPosition=R.prototype.P;R.prototype.getTotalDuration=R.prototype.ca;R.prototype.getState=R.prototype.J;R.prototype.getCurrentPlayTime=R.prototype.X;
R.prototype.getBitrate=R.prototype.T;R.prototype.getThumbnailPath=R.prototype.ba;R.prototype.getPlayerType=R.prototype.Z;R.prototype.getViewStartTime=R.prototype.da;R.prototype.getAuthors=R.prototype.Q;R.prototype.getSections=R.prototype.$;R.prototype.getAutoplayType=R.prototype.S;R.verify=function(a){return a===window.brightcove};R.prototype.getStrategyName=R.prototype.aa;R.prototype.getHost=R.prototype.Mb;R.prototype.getUid=R.prototype.Nb;function S(){this.a=window.flowplayer();this.D=this.G=j;this.B=u();this.ya=this.Ca=d;this.Ab=this.Xa="";this.Sb=d;this.ha()}var Mc=/url\(['"]?([^'"\)]*)['"]?\)/;n=S.prototype;
n.xc=function(){if(this.a.conf&&(this.Ab=this.a.conf.title?this.a.conf.title:"",this.Xa=this.a.conf.poster?this.a.conf.poster:"",this.Ab&&this.Xa))return g;var a=this.N(),b=ab("name","param"),c=d;t(b,function(b){if(b.attributes.name&&b.attributes.name.value==="flashvars"&&b.value.indexOf(a)!==-1)return c=b,j});c===d&&(b=ab("src","video"),t(b,function(b){if(b.attributes.src.value&&a.indexOf(b.attributes.src.value)!=-1)return c=b,j}));b=bb(c,"data-swf")||bb(c,"poster");if(b===j)return j;this.Xa=b.attributes.poster&&
b.attributes.poster.value;if(!this.Xa){var e=b.style.background;if(e&&(e=e.match(Mc)))this.Xa=e[1]}this.Ab=b.title;if(this.Sb!==d)clearInterval(this.Sb),this.G=g;return g};n.ha=function(){this.a.te?this.oa():this.a.bind("ready",s(this.oa,this));this.a.bind("resume",s(this.fa,this));this.a.se&&this.fa()};n.oa=function(){this.xc()===j?this.Sb=setInterval(s(this.xc,this),1E3):this.G=g};n.fa=function(){if(!this.D)this.D=g};n.O=l("G");n.M=l("Ab");n.N=function(){return this.a.video.url||this.a.video.src};
n.U=function(){return M};n.P=m("");n.ca=function(){return this.a.video.duration&&this.a.video.duration*1E3};n.J=function(){return!this.D?O:this.a.qe?"s4":this.a.paused?"s3":"s2"};n.X=function(){return y(this.a.video.time)};n.T=m(-1);n.ba=l("Xa");n.Z=k();n.S=k();n.da=function(){return isNaN(this.B)?0:Qa(this.B)};n.$=l("Ca");n.Q=l("ya");n.aa=m("FP");S.prototype.getStrategyName=S.prototype.aa;S.prototype.isReady=S.prototype.O;S.prototype.getTitle=S.prototype.M;S.prototype.getVideoPath=S.prototype.N;
S.prototype.getContentType=S.prototype.U;S.prototype.getAdPosition=S.prototype.P;S.prototype.getTotalDuration=S.prototype.ca;S.prototype.getState=S.prototype.J;S.prototype.getCurrentPlayTime=S.prototype.X;S.prototype.getBitrate=S.prototype.T;S.prototype.getThumbnailPath=S.prototype.ba;S.prototype.getPlayerType=S.prototype.Z;S.prototype.getAutoplayType=S.prototype.S;S.prototype.getViewStartTime=S.prototype.da;S.prototype.getSections=S.prototype.$;S.prototype.getAuthors=S.prototype.Q;S.verify=function(){return!!window.flowplayer};function T(a){this.a=a;this.Db=this.D=this.G=j;this.B=u();this.ya=this.Ca=d;this.ha()}n=T.prototype;n.ha=function(){this.a.readyState>0&&this.oa();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.fa();this.a.addEventListener("canplay",v(this.oa,this));var a=v(this.fa,this);this.a.addEventListener("playing",a);this.a.addEventListener("webkitbeginfullscreen",a);this.a.addEventListener("webkitendfullscreen",v(this.Zd,this))};n.oa=function(){this.G=g};n.fa=function(){this.D=g;this.Db=j};
n.Zd=function(){this.Db=g};n.O=l("G");n.M=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};n.N=function(){return this.a.currentSrc||""};n.U=function(){return M};n.P=m("");n.ca=function(){return y(this.a.duration)};n.J=function(){return!this.D?O:this.a.ended||this.Db&&this.a.currentTime==this.a.duration?"s4":this.a.paused||this.Db?"s3":"s2"};n.X=function(){return y(this.a.currentTime)};n.T=m(-1);n.ba=function(){return this.a.poster||""};n.Z=k();
n.S=function(){return this.a.autoplay?"auto":"man"};n.da=function(){return Sa(this.B)};n.$=l("Ca");n.Q=l("ya");n.aa=m("H5");T.prototype.getStrategyName=T.prototype.aa;T.prototype.isReady=T.prototype.O;T.prototype.getTitle=T.prototype.M;T.prototype.getVideoPath=T.prototype.N;T.prototype.getContentType=T.prototype.U;T.prototype.getAdPosition=T.prototype.P;T.prototype.getTotalDuration=T.prototype.ca;T.prototype.getState=T.prototype.J;T.prototype.getCurrentPlayTime=T.prototype.X;
T.prototype.getBitrate=T.prototype.T;T.prototype.getThumbnailPath=T.prototype.ba;T.prototype.getPlayerType=T.prototype.Z;T.prototype.getAutoplayType=T.prototype.S;T.prototype.getViewStartTime=T.prototype.da;T.prototype.getSections=T.prototype.$;T.prototype.getAuthors=T.prototype.Q;T.verify=function(a){var b=a instanceof HTMLElement&&a.nodeName==="VIDEO",a=a.getAttribute&&a.getAttribute("data-account")!==i;return b&&!a};function U(a){this.a=a;this.D=this.za=this.G=j;this.B=u();this.cb=j;this.ha()}n=U.prototype;n.ha=function(){function a(a,f){f=s(f,c);if(aa(b.on)=="function")b.on(a,f);else{var h="on"+a.substr(0,1).toUpperCase()+a.substr(1);if(aa(b[h])=="function")b[h](f)}}var b=this.a,c=this;a("ready",this.oa);a("time",this.Vd);a("complete",this.Wd);a("adStarted",this.Ta);a("adPlay",this.Ta);a("adImpression",this.Ta);a("adTime",this.Ta);a("adComplete",this.Wb);a("adSkipped",this.Wb);a("adError",this.Wb)};
n.oa=function(){this.G=g};n.Vd=function(){this.za=j;this.D=g;this.cb=j};n.Wd=function(){this.za=g};n.Ta=function(){this.cb=this.D=g};n.Wb=function(){this.cb=j};n.O=function(){this.a.getState();return this.G||this.a.getState()!==d};n.M=function(){var a=Nc(this);return!a?"":a.title};function Nc(a){if(a.a.getPlaylistIndex===d)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return i;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?i:b[a]}
n.N=function(){var a=Nc(this);return!a?"":a.mediaid||a.file};n.U=function(){return this.cb?"ad":M};n.P=m("");n.ca=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};n.J=function(){if(!this.D)return O;if(this.cb)return"s2";if(this.za)return"s4";var a=this.a.getState();return a&&a.toUpperCase()==="PAUSED"?"s3":"s2"};n.X=function(){var a=this.a.getPosition();return y(a)};n.T=m(-1);n.ba=function(){var a=Nc(this);return!a?"":a.image};n.Z=k();n.da=function(){return isNaN(this.B)?0:Qa(this.B)};
n.Q=k();n.$=k();n.S=m("unkn");n.aa=m("JW");U.prototype.getStrategyName=U.prototype.aa;U.prototype.isReady=U.prototype.O;U.prototype.getTitle=U.prototype.M;U.prototype.getVideoPath=U.prototype.N;U.prototype.getContentType=U.prototype.U;U.prototype.getAdPosition=U.prototype.P;U.prototype.getTotalDuration=U.prototype.ca;U.prototype.getState=U.prototype.J;U.prototype.getCurrentPlayTime=U.prototype.X;U.prototype.getBitrate=U.prototype.T;U.prototype.getThumbnailPath=U.prototype.ba;
U.prototype.getPlayerType=U.prototype.Z;U.prototype.getViewStartTime=U.prototype.da;U.prototype.getAuthors=U.prototype.Q;U.prototype.getSections=U.prototype.$;U.prototype.getAutoplayType=U.prototype.S;U.verify=function(a){return w(a.id)&&w(a.registerPlugin)};function V(a){this.a=a;this.Tc="";this.ia=O;this.Aa=M;this.sa="";this.B=u();this.ha()}n=V.prototype;n.ha=function(){this.a.kBind("playerStateChange.cb",s(this.Yd,this));this.a.kBind("playerUpdatePlayhead.cb",s(this.Qd,this));this.a.kBind("playerPlayEnd.cb",s(this.Xd,this));this.a.kBind("adStart.cb",s(this.Ta,this));this.a.kBind("adEnd.cb",s(this.Dd,this));this.a.kBind("switchingChangeComplete.cb",s(this.Ud,this))};
n.Yd=function(a){switch(a){case "playing":this.ia="s2";break;case "buffering":this.ia="s3";break;case "paused":this.ia="s3"}};n.Qd=function(){this.ia="s2";this.a.kUnbind("playerUpdatePlayhead.cb")};n.Xd=function(){this.ia="s4"};n.Ta=function(a){this.Aa="ad";switch(a){case "pre":this.sa="a1";break;case "post":this.sa="a3";break;case "mid":this.sa="a2";break;case "main":this.sa="a5"}};n.Dd=function(){this.Aa=M};n.Ud=function(a,b){this.ed=b};
n.O=function(){return this.a.evaluate("{mediaProxy.entry.name}")!=i};n.M=function(){return this.a.evaluate("{mediaProxy.entry.name}")};n.N=function(){if(!this.O())return this.Tc;var a=this.a.evaluate("{mediaProxy.entry.id}");return(this.Tc=a)||""};n.U=l("Aa");n.P=l("sa");n.ca=function(){var a=this.a.evaluate("{duration}");return y(a)};n.J=l("ia");n.X=function(){var a=this.a.evaluate("{video.player.currentTime}");return y(a)};n.T=l("ed");
n.ba=function(){return this.a.evaluate("{mediaProxy.entry.thumbnailUrl}")||""};n.Z=k();n.S=function(){var a=this.a.evaluate("{configProxy.flashvars.autoPlay}"),b=this.a.evaluate("{configProxy.flashvars.playlistAPI.autoContinue}"),c=this.a.evaluate("{playlistAPI.dataProvider.selectedIndex}");return b&&c>0?"cont":a?"auto":"man"};n.da=function(){return isNaN(this.B)?0:Sa(this.B)};n.$=function(){var a=this.a.evaluate("{mediaProxy.entry.tags}");if(a)return a.split(",")};
n.Q=function(){var a=this.a.evaluate("{mediaProxy.entry.creatorId}");if(a)return[encodeURIComponent(a)]};n.aa=m("KT");V.prototype.getStrategyName=V.prototype.aa;V.prototype.isReady=V.prototype.O;V.prototype.getTitle=V.prototype.M;V.prototype.getVideoPath=V.prototype.N;V.prototype.getContentType=V.prototype.U;V.prototype.getAdPosition=V.prototype.P;V.prototype.getTotalDuration=V.prototype.ca;V.prototype.getState=V.prototype.J;V.prototype.getCurrentPlayTime=V.prototype.X;V.prototype.getBitrate=V.prototype.T;
V.prototype.getThumbnailPath=V.prototype.ba;V.prototype.getPlayerType=V.prototype.Z;V.prototype.getAutoplayType=V.prototype.S;V.prototype.getViewStartTime=V.prototype.da;V.prototype.getSections=V.prototype.$;V.prototype.getAuthors=V.prototype.Q;V.verify=function(a){return typeof a.kBind=="function"};function W(a){this.rc=d;this.a=a;this.Cc=d;this.G=j;this.La=d;this.D=j;this.ya=this.Ca=this.B=d;this.rc=q.OO;this.Cc=this.a.mb;this.B=u();this.ha()}n=W.prototype;
n.ha=function(){var a=this.Cc,b=this.rc.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",s(this.oa,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",s(this.Fd,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",s(this.fa,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",s(this.Ed,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",s(this.Pd,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",s(this.Kd,this))};n.oa=function(){this.G=g};
n.Fd=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.La=a===0?"a1":Oc(a,b)?"a3":"a2"};n.fa=function(){this.D=g};n.Ed=function(){this.La=d};n.Pd=k();n.O=function(){var a=this.a.getState();if(a==="ready"||a==="playing"||a==="paused")this.G=g;return this.G};n.M=function(){var a=this.a.getItem();return a?a.title:""};
n.N=function(){var a=this.a.getEmbedCode&&this.a.getEmbedCode();if(a)return a;a=this.a.getItem()||{};return a.embed_code||a.embedCode||this.a.embedCode||""};n.U=function(){return this.La===d?M:"ad"};n.P=function(){return this.La?this.La:""};n.ca=function(){var a=this.a.getItem(),a=a&&a.duration||this.a.getDuration()*1E3;return a===-1||!isFinite(a)?-1:a};
n.J=function(){if(!this.D)return O;if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return Oc(a,b)?"s4":"s2"};function Oc(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}n.Kd=function(){this.La=d};n.X=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};
n.T=function(){var a=this.a.getCurrentBitrate&&this.a.getCurrentBitrate();return a?a.bitrate:0};n.ba=function(){var a=this.a.getItem();return!a?"":a.promo||a.promo_image||a.thumbnail_image};n.Z=k();n.S=k();n.da=function(){return isNaN(this.B)?0:Sa(this.B||0)};n.$=l("Ca");n.Q=l("ya");n.aa=m("OO");W.prototype.getStrategyName=W.prototype.aa;W.prototype.isReady=W.prototype.O;W.prototype.getTitle=W.prototype.M;W.prototype.getVideoPath=W.prototype.N;W.prototype.getContentType=W.prototype.U;
W.prototype.getAdPosition=W.prototype.P;W.prototype.getTotalDuration=W.prototype.ca;W.prototype.getState=W.prototype.J;W.prototype.getCurrentPlayTime=W.prototype.X;W.prototype.getBitrate=W.prototype.T;W.prototype.getThumbnailPath=W.prototype.ba;W.prototype.getPlayerType=W.prototype.Z;W.prototype.getAutoplayType=W.prototype.S;W.prototype.getViewStartTime=W.prototype.da;W.prototype.getSections=W.prototype.$;W.prototype.getAuthors=W.prototype.Q;
W.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("isAdPlaying")};function Y(a){this.a=a;this.ga=i;this.ab="";this.ia=O;this.Aa=M;this.sa="";this.B=u();this.a.controller.plugInLoaded&&this.a.controller.plugInLoaded(this)}n=Y.prototype;n.Ad=function(a){this.ha(a.controller)};
n.ha=function(a){a.addEventListener("OnLoadRelease",v(this.Gc,this));a.addEventListener("OnLoadReleaseUrl",v(this.Gc,this));a.addEventListener("OnReleaseStart",v(this.Sd,this));a.addEventListener("OnMediaPlay",v(this.Md,this));a.addEventListener("OnMediaStart",v(this.Od,this));a.addEventListener("OnMediaPause",v(this.Yb,this));a.addEventListener("OnMediaComplete",v(this.Ld,this));a.addEventListener("OnMediaError",v(this.Yb,this));a.addEventListener("OnMediaBuffer",v(this.Yb,this));a.addEventListener("OnMediaPlaying",
v(this.Nd,this))};n.Gc=function(a){if(a.data&&a.data.title)this.ga=a.data;if(a.data&&a.data.guid)this.ab=a.data.guid};n.Sd=function(a){t(a.data.clips,v(function(a){if(a=a.baseClip.guid)return this.ab=a,j},this));if(this.ab&&a.data.release&&a.data.release.title)this.ga=a.data.release};n.Md=function(){this.ia="s2"};n.Od=function(a){this.ia="s2";a=a.data.baseClip;a.isAd?(this.Aa="ad",this.sa=a.isMid?"a2":"a1"):(this.Aa=M,this.sa="")};n.Yb=function(){if(this.ia!=O)this.ia="s3"};
n.Ld=function(){this.ia="s4"};n.Nd=function(a){this.jd=a.currentTime};n.O=function(){return this.ga!=i};n.M=function(){return this.ga.title};n.N=function(){return!this.ab?"":this.ab};n.U=l("Aa");n.P=l("sa");n.ca=function(){return this.ga.duration};n.J=l("ia");n.X=l("jd");n.T=function(){return this.ga.bitrate};n.ba=function(){return this.ga&&this.ga.defaultThumbnailUrl?this.ga.defaultThumbnailUrl:this.ga.pid?"http://link.theplatform.com/s/ngc/"+this.ga.pid+"?format=poster&height=70&width=95":""};
n.Z=k();n.S=k();n.da=function(){return isNaN(this.B)?0:this.B===d?0:u()-this.B};n.$=function(){var a=this.ga.keywords?this.ga.keywords.split(","):[],b=[];t(this.ga.categories?this.ga.categories:[],function(a){b.push(encodeURIComponent(a.name))});t(a,function(a){b.push(encodeURIComponent(a.trim()))});return b};n.Q=k();n.aa=m("TP");Y.prototype.initialize=Y.prototype.Ad;Y.prototype.getStrategyName=Y.prototype.aa;Y.prototype.isReady=Y.prototype.O;Y.prototype.getTitle=Y.prototype.M;
Y.prototype.getVideoPath=Y.prototype.N;Y.prototype.getContentType=Y.prototype.U;Y.prototype.getAdPosition=Y.prototype.P;Y.prototype.getTotalDuration=Y.prototype.ca;Y.prototype.getState=Y.prototype.J;Y.prototype.getCurrentPlayTime=Y.prototype.X;Y.prototype.getBitrate=Y.prototype.T;Y.prototype.getThumbnailPath=Y.prototype.ba;Y.prototype.getPlayerType=Y.prototype.Z;Y.prototype.getAutoplayType=Y.prototype.S;Y.prototype.getViewStartTime=Y.prototype.da;Y.prototype.getSections=Y.prototype.$;
Y.prototype.getAuthors=Y.prototype.Q;Y.verify=function(a){return typeof a.controller!=="undefined"};function Pc(a,b){this.a=a;this.Sc=b;this.Oa=window.location!=window.parent.location;this.Kc=j;this.ge=u();this.Rc="_v_";this.ta={};Wb.call(this)}ea(Pc,Wb);var Qc=q.QUICK_TEST?1E4:6E4,Rc="autoDetect",Sc={me:"title",ne:"videopath",le:"thumbnailpath"},Tc={};n=Pc.prototype;
n.H=function(){this.Ub=(this.Ua=this.q.F("_chartbeat3"))?0:1;this.mc=this.ec=g;this.Kb=j;this.wb=this.bc=this.uc=this.Ha=d;this.Ma=15E3;this.jb=d;this.kb=this.lb=0;this.Lb=j;this.$d=this.jc=this.Bb=0;this.cc=j;if(!this.Ua||this.Ua.length===0)this.Ua=qa(Xb(this),3);this.q.create("_chartbeat3",this.Ua,34128E3);var a;(a=this.Sc)&&Ja(a)?(this.ea=new a(this.a),a=g):a=j;if(a){a=!!this.k.useCanonical;var b=Pb(!!this.k.useCanonicalDomain&&a);C(this.k,"pingServer","ping.chartbeat.net");C(this.k,"title",document.title);
C(this.k,"domain",b);this.k.path=this.k.path?I(this.k.path):Nb(a);this.k.domain=ta(this.k.domain);this.ea.getPlayerType&&C(this.k,"video_type",this.ea.getPlayerType());this.uc=setInterval(v(this.fd,this),1E3);if(this.Oa===g)this.sb=v(this.wd,this),Ga(window,"message",this.sb),this.jb=setInterval(this.ae,1E3);Pc.ka.H.call(this)}};n.Hb=k();
n.na=function(){if(this.ea){if(!Uc(this))this.mc=g;if(!this.mc)return u()-this.Ga>=this.rb&&clearInterval(this.Ha),Pc.ka.na.call(this);if(this.ea.isReady())this.Kb=this.mc=j,this.bc=Vc(this),Wc(this),this.Ha=setInterval(v(this.Jb,this),100),Pc.ka.na.call(this);else if(!this.Kb){this.Kb=g;if(this.$d++>150)throw"Error: Video strategy never reported its ready state";Xc(this,100)}}};
n.Va=function(){if(this.ea){var a=this.k,b=this.ea,c=b.getState(),e=Uc(this),f=this.Oa?[]:q._cbq||(q._cbq=[]),h=b.getViewStartTime(),o=Yc(this),r=b.getAutoplayType?b.getAutoplayType():d,h=h===-1?-1:h/1E3,o=o?encodeURIComponent(o):d;if(!Tc.path||Tc.path===e||c==="s2"&&Tc.state!=="s2")switch(Tc={path:e,state:c},f.push(["_vi",La(Zc(this))]),f.push(["_vp",e]),f.push(["_vdd",La($c(this))]),f.push(["_vs",b.getState()]),b.getContentType&&f.push(["_vt",b.getContentType()]),b.getAdPosition&&f.push(["_vap",
b.getAdPosition()]),f.push(["_vtn",La(Yc(this))]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case O:case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}a=ad(this)+Z("_vt",b.getContentType?b.getContentType():"")+Z("_vap",b.getAdPosition?b.getAdPosition():"")+Z("_vs",c)+Z("_vcs",this.Lb?"1":"0")+Z("_vbr",b.getBitrate?b.getBitrate():"")+Z("_vvs",h)+Z("_vpt",b.getCurrentPlayTime())+Z("_vtn",o)+Z("_vaup",r||"unkn")+Z("_vplt",a.video_type)+Z("_vce",this.jc)+Z("c",Math.round(Qa(this.ge)/
600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.Bb+"&j="+(this.Ma/1E3+15)+bd(this)+"&tz="+(new Date).getTimezoneOffset()+(Mb(this.q)?"&l=1":"")+"&_";this.Oa===g&&t(f,function(a){window.top.postMessage("cbqpush::"+a.join("::"),"*")});this.hb(a)}};function Z(a,b){return b!==d&&b!==""?"&"+a+"="+b:""}n.fb=function(){this.q.update("_cb_cp",this.Da,60,j,",")};function bd(a){var b=a.q.F("_cb_cp");a.q.remove("_cb_cp");return b?"&D="+b:""}
function cd(a){return a.k.subdomain?a.k.subdomain:ta(q.location.hostname)}function $c(a){var b=a.k,a=a.ea,b=b.videodomain||a.getHost&&a.getHost()||b.domain;return"video@"+(b&&b.replace(/^video@/,""))}function Uc(a){var b=a.ta.videopath;if(b)return b;if(a.k.videoPathHash){if(a=Zc(a))return qa(a)}else return a.ea.getVideoPath();return""}function Zc(a){return a.ta.title||a.ea.getTitle()}function Yc(a){return a.ta.thumbnailpath||a.ea.getThumbnailPath()}
function ad(a){var b=a.k,c=a.ea,e=c.getUid&&c.getUid()||b.uid,f=La($c(a)),h="",o=a.gb?"&b="+a.gb:"",r,p=a.k.path;r=a.k.useSubDomains!==j&&p&&p.substr(0,1)==="/"?cd(a)+p:p;var p=c.getSections&&c.getSections(),D=c.getAuthors&&c.getAuthors(),F=b.sections?"&g0="+encodeURIComponent(b.sections):"",Q=b.authors?"&g1="+encodeURIComponent(b.authors):"",p=p===d||b.videoPageGroups?F:"&g0="+encodeURIComponent(p.join(",")),D=D===d||b.videoPageGroups?Q:"&g1="+encodeURIComponent(D.join(",")),Q="",F=Uc(a);if(a.wb===
d)a.wb=F;else if(F!=a.wb)Q=Z("D",a.Da),a.Da=qa(Xb(a)),a.wb=F,a.lb=0,a.kb=0,a.Bb=0,a.jc=0,a.Lb=dd(a)&&!ed(a),a.ec=g;if(a.ec||Q){if(a.Oa===j||a.Oa===g&&a.Kc===g)a.ec=j;h=(Yb(a)?"&v=":"&r=")+Zb(a)}a.Bb+=a.lb;a.lb=0;a.jc+=a.kb;a.kb=0;Wc(a);var X=F="",ha="",da="",N="",E="",la="",ma="";if(!a.Oa===g||a.cc===g)F="&_vi="+fc(a),X="&_vp="+encodeURIComponent(r),ha="&_vh="+La(cd(a)),da="&_vdd="+encodeURIComponent(b.domain),a.cc===g?(N=b.u,E=b.t,la=$a(b.v),ma=$a(b.r)):(N=J("u"),E=J("t"),la=$a(J("v")),ma=$a(J("r")));
r="";r=x(la)?"&_pv="+la:x(ma)?"&_pr="+ma:"&_pr=NA";la="&_pu=";ma="&_pt=";la+=N?N:"NA";ma+=E?E:"NA";N=!b.noCookies&&a.q.isSupported();E=c.getStrategyName?c.getStrategyName():"";return Ma()+"//"+b.pingServer+"/ping?h="+f+"&g="+e+"&p="+La(Uc(a))+"&i="+La(Zc(a))+p+D+"&u="+a.Ua+"&t="+a.Da+"&x=0&y=0&V=100"+Z("VS",E)+(N?"&n="+a.Ub:"&nc=1")+o+h+Q+Z("_vd",c.getTotalDuration())+F+X+ha+la+ma+r+da}n.Jb=function(){if(dd(this)&&!ed(this))this.Lb=g;var a=Vc(this);if(this.bc!=a)this.bc=a,Wc(this),this.na()};
function Wc(a){var b=a.Ma;a.Ma=dd(a)?a.Bb<60?5E3:15E3:Qc;b!=a.Ma&&Xc(a,a.Ma)}function Xc(a,b){clearInterval(a.ob);a.Ma=b;a.ob=setInterval(v(a.na,a),b)}function Vc(a){return a.ea.getState()+a.ea.getContentType()}function dd(a){return a.ea.getState()==="s2"||ed(a)}function ed(a){return a.ea.getContentType()==="ad"}n.fd=function(){dd(this)===g&&(this.lb+=1,this.ea.getContentType()===M&&(this.kb+=1))};n.ae=function(){window.parent.postMessage("cbdata?","*")};
n.wd=function(a){if(a.source===window.parent&&(a=a.data,x(a)&&a.indexOf("domain=")===0)){this.cc=g;var b={domain:g,uid:g,path:g,title:g,referrer:g,internal:g,subdomain:g,token:g,u:g,t:g,v:g,r:g},c=this;t(a.split("&"),function(a){var a=a.split("="),f=a[0],a=a[1];b[f]&&(c.k[f]=decodeURIComponent(a))});Ha(window,"message",this.sb);clearInterval(this.jb);this.jb=d;this.Kc=g;this.na()}};n.setProperty=function(a,b){var c=j,e=this;t(Sc,function(f){if(a.toLowerCase()==f)return e.ta[f]=b,c=g,j});return c};
n.terminate=function(){clearInterval(this.uc);clearInterval(this.jb);clearInterval(this.Ha);Ha(window,"message",this.sb);Pc.ka.terminate.call(this)};n.wa=function(){Pc.ka.wa.call(this);this.Sc=this.a=this.sb=i};function $(a){this.a=a;this.G=g;this.D=j;this.B=u();this.Ha=this.ya=this.Ca=d;this.ha()}n=$.prototype;n.ha=function(){this.Ha=setInterval(s(this.Jb,this),100);var a=this.a.getPlayerState();(a===1||a===2||a===0)&&this.fa()};n.Jb=function(){if(this.a.getPlayerState()===1)clearInterval(this.Ha),this.Ha=d,this.fa()};n.fa=function(){if(!this.D)this.D=g};function fd(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}n.O=l("G");
n.M=function(){var a="";Ja(this.a.getVideoData)&&(a=(a=this.a.getVideoData())&&a.title||"");return a};n.N=function(){return fd(this)||this.a.getVideoUrl()};n.U=function(){return M};n.P=m("");n.ca=function(){var a=this.a.getDuration();return Ia(a)?a*1E3:a};n.J=function(){if(!this.D)return O;var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};n.X=function(){var a=this.a.getCurrentTime();return y(a)};n.T=m(-1);n.ba=function(){return"http://img.youtube.com/vi/"+fd(this)+"/default.jpg"};
n.Z=k();n.S=k();n.da=function(){return isNaN(this.B)?0:Qa(this.B)};n.$=l("Ca");n.Q=l("ya");n.aa=m("YT");$.prototype.getStrategyName=$.prototype.aa;$.prototype.isReady=$.prototype.O;$.prototype.getTitle=$.prototype.M;$.prototype.getVideoPath=$.prototype.N;$.prototype.getContentType=$.prototype.U;$.prototype.getAdPosition=$.prototype.P;$.prototype.getTotalDuration=$.prototype.ca;$.prototype.getState=$.prototype.J;$.prototype.getCurrentPlayTime=$.prototype.X;$.prototype.getBitrate=$.prototype.T;
$.prototype.getThumbnailPath=$.prototype.ba;$.prototype.getPlayerType=$.prototype.Z;$.prototype.getAutoplayType=$.prototype.S;$.prototype.getViewStartTime=$.prototype.da;$.prototype.getSections=$.prototype.$;$.prototype.getAuthors=$.prototype.Q;$.verify=function(a){return Ja(a.getDuration)&&Ja(a.getVideoUrl)&&Ja(a.getVideoEmbedCode)};function gd(){q._cbv_strategies||(q._cbv_strategies=[]);q._cbv_strategies.push(W);q._cbv_strategies.push(T);q._cbv_strategies.push(S);q._cbv_strategies.push($);q._cbv_strategies.push(U);q._cbv_strategies.push(R);q._cbv_strategies.push(P);q._cbv_strategies.push(V);q._cbv_strategies.push(Y);this.kc=[];this.ta=[];this.k=q._sf_async_config||{};Gb("_cbv",v(this.xd,this));if(this.k[Rc]!==j)this.nd=Ya(v(this.yc,this),5E3),this.yc(),setTimeout(v(this.Ia,this),3E4)}
gd.prototype.xd=function(a){if(aa(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){hd();return}else if(b==="removePlayer"){id(this,a[1]);return}else if(b==="setProps"){jd(a[1])||this.ta.push(a[1]);return}}kd(this,a)};function kd(a,b){var c=j,e=q._cbv_strategies;w(window.jwplayer)&&(b=Ja(b)?b():b);t(e,function(a){if(a.verify(b)===g)return c=a,j});c===j||ld(a,b,c)}
function id(a,b){var c=a.kc,e=q.pSUPERFLY_video,f=Oa(c,function(a){return b===a});f!==-1&&c.splice(f,1);f=Oa(e,function(a){return a.a===b});f!==-1&&e.splice(f,1)[0].wa()}function jd(a){if(!w(a))return j;var b=a.player,c=Pa(function(a){return a.a===b});return!w(c)?j:md(c,a)}function md(a,b){var c=j;t(b,function(b,f){if(f!=="player"&&(c=a.setProperty(f,b),!c))return c});return c}
function ld(a,b,c){var e=j;t(a.kc,function(a){if(b===a)return e=g,j});if(!e){c=new Pc(b,c);q.pSUPERFLY_video.push(c);for(var f=a.ta.length-1;f>-1;f--)md(c,a.ta[f])&&a.ta.splice(f,1);bc(c);a.kc.push(b)}}
gd.prototype.yc=function(){if(Ja(window.jwplayer)&&w(window.jwplayer())){this.Ia();for(var a=0,b=window.jwplayer(a);w(b.id);)window._cbv.push(b),b=window.jwplayer(++a)}else window.flowplayer?(this.Ia(),window._cbv.push(window.flowplayer)):window.brightcove&&window.experienceJSON?(this.Ia(),window._cbv.push(window.brightcove)):window.videojs?(this.Ia(),a=window.videojs.plugin,Ja(a)&&a("chartbeat",function(a){this.cb_configs=a;window._cbv.push(this)})):window.kWidget?(this.Ia(),window.kWidget.addReadyCallback(function(a){window._cbv.push(document.getElementById(a))})):
window.$pdk?(this.Ia(),window._cbv.push(window.$pdk)):t(document.getElementsByTagName("video"),function(a){window._cbv.push(a)})};gd.prototype.Ia=function(){Va(this.nd)};
function hd(){function a(){function a(b){q._cbv.push(b.target)}var b=q.YT.Player;t(document.getElementsByTagName("iframe"),function(f){var h=f.src,o=h&&h.indexOf("www.youtube.com/embed/");h&&o>=0&&o<9&&new b(f,{events:{onReady:a}})})}if(q.YT&&q.YT.Player)a();else{var b=q.onYouTubeIframeAPIReady;q.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(q,arguments)}catch(c){}a()}}}};function nd(a,b){return function(c,e){if(!qb){a();var f=q._sf_async_config,h="",o=f.path,o=va(o);/^\//.test(o)&&(h=ta(q.location.hostname));f.virtualReferrer=Ma()+"//"+h+o;if(x(c))f.path=I(c),e&&(f.title=e);else if(Na(c)){var r=["authors","sections","title","path"];t(c,function(a,b){if(Oa(r,function(a){return a===b})!==-1||b.indexOf("_")===0)f[b]=b==="path"?I(a):a})}b()}}};if(window.location==window.parent.location&&!q.pSUPERFLY){var od=new Gc,pd={};q.pSUPERFLY=pd;var qd=!!yc;pd.virtualPage=nd(function(){od.nb();qd&&yc.evps()},function(){od.Qc();qd&&yc.svps()});pd.activity=v(od.Zc,od);bc(od);var rd=H.Y(g);if(!rd?0:rd.getItem("_cb_ip")){var sd=q.location;(!/^(.+[.])?chartbeat\.com$/.test(sd.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(sd.pathname))||Ec()}else Ga(q,"message",Fc)}q.pSUPERFLY_video||(q.pSUPERFLY_video=[]);new gd;})();
